/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef GPADC_POWER_H_
#define GPADC_POWER_H_

#include "ffs.h"
#include <stddef.h>
#include <sunxi_hal_power.h>
#include <sunxi_hal_gpadc.h>
#include <sunxi_hal_power_private.h>
#include <sunxi_hal_gpadc.h>

#define GPADC_MANUFACTURER  "xpower,gpadc"

#define VBUS_DETECT_NO_CHARGE_VAL 2471    // 不充电 mV
#define VBUS_DETECT_CHARGE_VAL    1708    // 充电 mV
#define VBUS_DETECT_FULL_VAL      2083    // 满 电 mV
#define VBUS_DETECT_ADC           0xffff // 0xffff 表示不使用该引脚, 如果要使用则改为类似 GP_CH_0
#define VBUS_DETECT_IO            0xffff  // 0xffff 表示不使用该引脚, 如果要使用则改为类似 GPIOA(12)
#define VBUS_ADC_COMPARE_LOWDATA  (2360000UL)
#define VBUS_ADC_COMPARE_HIGDATA  (2370000UL)
#define GPADC_POWER_CHANNEL       GP_CH_0

int gpadc_set_vbus_chg_plg_cb(gpadc_callback_t user_callback);

int gpadc_init_power(struct power_dev *rdev);

int gpadc_get_power(struct power_dev *rdev);

int hal_power_low_power_detect(unsigned int low_power_value);


#endif /* GPADC_POWER_H_ */
