/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY��S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS��SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY��S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __GPADC_SUN20IW2_H__
#define __GPADC_SUN20IW2_H__

#if defined(CONFIG_ARCH_RISCV_C906)
#define SUNXI_GPADC_IRQ	137
#elif defined(CONFIG_ARCH_DSP)
#define SUNXI_GPADC_IRQ	122
#else
#define SUNXI_GPADC_IRQ	121
#endif

#define GPADC_BASE      0x4004a000
#define GPADC_CLOCK     (20000000UL)
#define OSC_24MHZ       (1000000UL)
#define MAX_SR          (1000000UL)     // 定义GPADC的最大采样率为1MHz
#define MIN_SR          (400UL)         // 定义GPADC的最小采样率为400Hz
#define DEFAULT_SR      (5000UL)        // 定义GPADC的默认采样率为5000Hz
/* voltage range 0~2.5v, unit is uv */
#define VOL_RANGE       (2500000UL)     // 定义GPADC的电压范围为0~2.5V, 这个值用于将ADC原始采样值转换为实际电压值的计算
#define VOL_VALUE_MASK      (0Xfff)      // 定义GPADC的电压值掩码, ADC采样值的掩码为0x0fff（12位），表明ADC分辨率为12位
#define COMPARE_LOWDATA   1700000UL     // 定义GPADC的低电压比较值为1.7V, 当电压低于1.7V时触发低电压中断
#define COMPARE_HIGDATA   1200000UL     // 定义GPADC的高电压比较值为1.2V, 当电压高于1.2V时触发高电压中断
#define POWER_PROTECT_LOWDATA   1000000UL     // 定义GPADC的低电压保护值为1.0V, 当电压低于1.0V时触发低电压保护
#define POWER_PROTECT_HIGDATA   1100000UL     // 定义GPADC的高电压保护值为1.1V, 当电压高于1.1V时触发高电压保护

#endif /* __GPADC_SUN20IW2_H__ */
