/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __CONFIG_H
#define __CONFIG_H

#if defined(CONFIG_DYNAMIC_FTRACE)
#define DYNAMIC_FTRACE                   1
#else
#define DYNAMIC_FTRACE                   0
#endif

#if defined(CONFIG_DYNAMIC_FTRACE)
#define DYNAMIC_FTRACE_CMD               1
#else
#define DYNAMIC_FTRACE_CMD               0
#endif

#if defined(CONFIG_DYNAMIC_FTRACE_GRAPH)
#define DYNAMIC_FTRACE_GRAPH             1
#else
#define DYNAMIC_FTRACE_GRAPH             0
#endif

#if defined(CONFIG_DYNAMIC_FTRACE_IRQSOFF)
#define DYNAMIC_FTRACE_IRQSOFF           1
#else
#define DYNAMIC_FTRACE_IRQSOFF           0
#endif

#if defined(CONFIG_DYNAMIC_FTRACE_KALLSYMS)
#define DYNAMIC_FTRACE_KALLSYMS          1
#else
#define DYNAMIC_FTRACE_KALLSYMS          0
#endif

#if defined(CONFIG_DYNAMIC_FTRACE_FILTER)
#define DYNAMIC_FTRACE_FILTER            1
#else
#define DYNAMIC_FTRACE_FILTER            0
#endif

#if defined(CONFIG_DYNAMIC_FTRACE_ISR_CALL_XIPFUNC_CHECK)
#define DYNAMIC_FTRACE_ISR_CALL_XIPFUNC_CHECK 1
#else
#define DYNAMIC_FTRACE_ISR_CALL_XIPFUNC_CHECK 0
#endif

#define DYNAMIC_FTRACE_SAVE_TO_RINGBUF   1
#define DYNAMIC_FTRACE_BACKTRACE         0
#define THREAD_STACK_SAVE_BY_LIST        \
	(DYNAMIC_FTRACE_GRAPH || DYNAMIC_FTRACE_IRQSOFF)

#if CONFIG_MAX_BUF_SIZE > 1
#define MAX_BUF_SIZE                     CONFIG_MAX_BUF_SIZE
#else
#define MAX_BUF_SIZE                     8192
#endif

#if CONFIG_MAX_FILTER_TABLE_SIZE > 1
#define MAX_TABLE_SIZE                   CONFIG_MAX_FILTER_TABLE_SIZE
#else
#define MAX_TABLE_SIZE                   64
#endif

#if CONFIG_INIT_TASK_STACK_SIZE > 1
#define INIT_TASK_STACK_SIZE             CONFIG_INIT_TASK_STACK_SIZE
#else
#define INIT_TASK_STACK_SIZE             1024
#endif

#if CONFIG_DEINIT_TASK_STACK_SIZE > 1
#define DEINIT_TASK_STACK_SIZE           CONFIG_DEINIT_TASK_STACK_SIZE
#else
#define DEINIT_TASK_STACK_SIZE           1024
#endif

#if CONFIG_CMD_TASK_STACK_SIZE > 1024
#define CMD_TASK_STACK_SIZE              CONFIG_CMD_TASK_STACK_SIZE
#else
#define CMD_TASK_STACK_SIZE              (10 * 1024)
#endif

#if CONFIG_CMD_TASK_PRI > 1
#define CMD_TASK_PRI                     CONFIG_CMD_TASK_PRI
#else
#define CMD_TASK_PRI                     2
#endif

#if CONFIG_FIND_MAX_INST_NUM > 50
#define FIND_MAX_INST_NUM                CONFIG_FIND_MAX_INST_NUM
#else
#define FIND_MAX_INST_NUM                500
#endif

#define INIT_TASK_PRI                    1
#define DEINIT_TASK_PRI                  1

#define EXIT_FREE_LR_STACK               0

#define DEBUG                            0
#endif /* __CONFIG_H */
