#asflags-y += -Idrivers/rtos-hal/hal/source/sound_v2/component/aw-audio-utils

obj-$(CONFIG_COMPONENTS_AW_TINY_SOUND_UTILS) += common.o
obj-$(CONFIG_COMPONENTS_AW_TINY_SOUND_UTILS) += wav_parser.o
obj-$(CONFIG_COMPONENTS_AW_TINY_SOUND_UTILS) += card.o
obj-$(CONFIG_COMPONENTS_AW_TINY_SOUND_UTILS_AWTINYPLAY) += aw_tinyplay.o
obj-$(CONFIG_COMPONENTS_AW_TINY_SOUND_UTILS_AWTINYCAP) += aw_tinycap.o
obj-$(CONFIG_COMPONENTS_AW_TINY_SOUND_UTILS_AWTINYMIXER) += aw_tinymixer.o
obj-$(CONFIG_COMPONENTS_AW_TINY_SOUND_UTILS_AWTINYLOOP) += aw_tinyloop.o
