obj-y := dev_lcd_fb.o disp_lcd.o
obj-y += lcd_fb_intf.o disp_display.o panels/panels.o panels/lcd_source.o panels/lcd_common_func.o

obj-${CONFIG_LCD_SUPPORT_KLD35512} += panels/kld35512.o
obj-${CONFIG_LCD_SUPPORT_KLD39501} += panels/kld39501.o
obj-${CONFIG_LCD_SUPPORT_KLD2844B} += panels/kld2844b.o
obj-${CONFIG_LCD_SUPPORT_NV3029S} += panels/nv3029s.o
obj-$(CONFIG_LCD_SUPPORT_JLT35031C) += panels/jlt35031c.o
obj-${CONFIG_LCD_SUPPORT_ST7796_SPI} += panels/st7796s.o
obj-${CONFIG_LCD_SUPPORT_ST7789V3} += panels/lcd_st7789v3.o
obj-${CONFIG_LCD_SUPPORT_AXS15231} += panels/lcd_axs15231.o
obj-${CONFIG_LCD_SUPPORT_AXS15231} += panels/lcd_common_func.o