/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __CE_PLATFORM_H
#define __CE_PLARFORM_H


#ifdef __cplusplus
extern "C"
{
#endif

/*define CE version*/
#define CE_SUPPORT_CE_V3_1

#define CE_NS_BASE_REG			(0x40004000)
#define CE_S_BASE_REG			(0x40004800)
#define CE_BASE_REG				CE_NS_BASE_REG

#if defined(CONFIG_ARCH_ARM_CORTEX_M33)
#define SUNXI_IRQ_CE_S			(79)
#define SUNXI_IRQ_CE_NS			(80)
#define SUNXI_IRQ_CE			(SUNXI_IRQ_CE_NS)
#elif defined(CONFIG_ARCH_RISCV_C906)
#define SUNXI_IRQ_CE_S			(95)
#define SUNXI_IRQ_CE_NS			(96)
#define SUNXI_IRQ_CE			(SUNXI_IRQ_CE_NS)
#else
#define SUNXI_IRQ_CE_S			(80)
#define SUNXI_IRQ_CE_NS			(81)
#define SUNXI_IRQ_CE			(SUNXI_IRQ_CE_NS)
#endif

#define SUNXI_CLK_CE CLK_BUS_SS
#define SUNXI_CLK_MBUS_CE CLK_MBUS_CE
#define SUNXI_RST_CE RST_SS

#define SUNXI_CCM_BASE			(0x03001000)
#define CCMU_CE_CLK_REG			(SUNXI_CCM_BASE + 0x680)
#define CCMU_CE_BGR_REG			(SUNXI_CCM_BASE + 0x68C)
#define MBUS_MAT_CLK_GATING_REG		(SUNXI_CCM_BASE + 0x804)

#define CE_CLK_SRC_MASK			(0x1)
#define CE_CLK_SRC_SEL_BIT		(24)
#define CE_CLK_SRC			(0x01)
#define CE_CLK_DIV_RATION_N_BIT		(8)
#define CE_CLK_DIV_RATION_N_MASK	(0x3)
#define CE_CLK_DIV_RATION_N		(0)

#define CE_CLK_DIV_RATION_M_BIT		(0)
#define CE_CLK_DIV_RATION_M_MASK	(0xF)
#define CE_CLK_DIV_RATION_M		(3)

#define CE_SCLK_ONOFF_BIT		(31)
#define CE_SCLK_ON			(1)

#define CE_GATING_PASS			(1)
#define CE_GATING_BIT			(0)
#define CE_RST_BIT			(16)
#define CE_DEASSERT			(1)

#endif
