/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __STANDBY_CLK_H__
#define __STANDBY_CLK_H__

#include "head.h"
#include "platform.h"

/* ccmu-aon */
#define DCXO_CTRL_REG			(CCMU_AON_BASE + 0x0088)
#define DCXO_EN_MASK			(0x1 << 31)
#define BUFFER_DPLL_EN			(0x1 << 9)

#define DPLL1_CTRL_REG			(CCMU_AON_BASE + 0x008c)
#define DPLL2_CTRL_REG			(CCMU_AON_BASE + 0x0090)
#define DPLL3_CTRL_REG			(CCMU_AON_BASE + 0x0094)
#define DPLL_EN_MASK			(0x1 << 31)
#define DPLL_NDIV_MASK			(0xff << 4)
#define DPLL_FACTORM_MASK		(0xf << 0)

#define AUDIO_PLL_CTRL_REG		(CCMU_AON_BASE + 0x0098)
#define AUDPLL_EN_MASK			(0x1 << 31)
#define AUDPLL_LOCK_EN_MASK		(0x1 << 29)
#define AUDPLL_LOCK_MASK		(0x1 << 28)
#define AUDPLL_FACTORN_MASK		(0x7f << 8)
#define AUDPLL_PRETDIVM_MASK		(0x1f << 0)

#define DPLL1_OUT_CFG_REG		(CCMU_AON_BASE + 0x00a4)
#define DPLL3_OUT_CFG_REG		(CCMU_AON_BASE + 0x00a8)
#define DPLL_OUT_CFG_LOCK_MASK		(0x1 << 30)

#define CLK_LDO_CTRL_REG		(CCMU_AON_BASE + 0x00ac)
#define CLK_LDO1_EN_MASK		(0x1 << 0)
#define CLK_LDO2_EN_MASK		(0x1 << 16)

#define MODULE_CLK_EN_CTRL		(CCMU_AON_BASE + 0x00cc)
#define GPIO_BUS_CLK_GATING_MASK	(0x1 << 11)

#define SYS_CLK_CTRL_REG		(CCMU_AON_BASE + 0x00e0)
#define M33_CLK_SRC_SEL_MASK		(0x3 << 12)
#define SYS_CLK_DIV_MASK		(0xf << 8)
#define APB_CLK_SRC_SEL_MASK		(0x3 << 6)
#define APB_CLK_DIV_MASK		(0x3 << 4)

#define APB_CLK_HOSC_SEL		(0x0 << 6)
#define APB_SYS_32K_SEL			(0x1 << 6)
#define APB_RCO_HF_SEL			(0x3 << 6)
#define APB_CLK_DIV_1_SEL		(0x0 << 4)
#define M33_CLK_HOSC_SEL		(0x0 << 12)
#define M33_SYS_32K_SEL			(0x1 << 12)
#define M33_RCO_HF_SEL			(0x3 << 12)
#define M33_CLK_DIV_1_SEL		(0x0 << 8)

/* MBUS: 0 DPLL1, 1 DPLL3; DIV default 8 */
#define CKPLL_HSPSRAM_SEL_MASK		(0x1 << 21)
#define MBUS_CLK_SEL_MASK		CKPLL_HSPSRAM_SEL_MASK

/* gprcm */
#define SYSTEM_PRIV_REG3		(GPRCM_BASE + 0x020c)

#define SYS_LFCLK_CTRL_REG		(GPRCM_BASE + 0x0080)
#define SYSRTC_32K_SEL_LFCLK		(0x0 << 25)
#define SYSRTC_32K_SEL_RCOCALIB		(0x1 << 25)
#define SYSRTC_32K_SEL_MASK		(0x3 << 25)
#define RC_HF_EN_MASK			(0x1 << 29)

#define SYS_RCOSC_FREQ_DET		(GPRCM_BASE + 0x0140)

/* standby status */
#define STANDBY_STATUS_REG		SYSTEM_PRIV_REG3
#define STANDBY_STATUS_SUSPEND		(0x10)
#define STANDBY_STATUS_RESUME		(0x20)

static inline void save_mem_status(volatile uint32_t val)
{
	writel(val, STANDBY_STATUS_REG);
}

void clk_suspend(standby_head_t *head);
void clk_resume(standby_head_t *head);

#endif /* __STANDBY_CLK_H__ */

