obj-$(CONFIG_DRIVERS_SUNXI_KEYBOARD) += sunxi-keyboard.o
obj-$(CONFIG_DRIVERS_GPIO_KEY_POLLED) += gpio_key_polled.o
obj-$(CONFIG_DRIVERS_GPADC_KEY) += gpadc-key.o
obj-$(CONFIG_DRIVERS_GPIO_KEY_NORMAL) += gpio_key_normal.o

