obj-y += common/

obj-$(CONFIG_COMPONENTS_OSTEST_FPU) += fpu_test/
obj-$(CONFIG_COMPONENTS_OSTEST_JPEGPERF) += jpegperf/
obj-$(CONFIG_COMPONENTS_OSTEST_OSAL) += osal_test/
obj-$(CONFIG_COMPONENTS_OSTEST_KERNEL) += kernel_test/

subdir-ccflags-y += -I components/common/aw/ostest/common/
