/*********************************************************************************
  *Copyright(C),2014-2022,GuRobot
  *Author:  weigang
  *Date:  2022.02.26
  *Description:  DOM 创建和属性设置函数对应表
  * 以下代码是通过python生成的，不要直接修改，
  * 修改 engine_data对应的xml文件，然后运行python3 gen_code.py生成
  *History:  
**********************************************************************************/
#ifndef GU_DOM_WIDGET_MAP_H
#define GU_DOM_WIDGET_MAP_H

#ifdef __cplusplus
extern "C" {
#endif

#include "gu_func_point_refact.h"

//自定义事件, 图片下载状态变化
#define GU_EVENT_IMG_HTTP_STATUS_CHANGED _LV_EVENT_LAST+1
#define GU_EVENT_FOCUS_CHANGED _LV_EVENT_LAST+2

#define MAX_DOM_COUNT 22
#define MAX_DOM_ATTR_COUNT 162
#define MAX_CSS_STYLE_MAP_COUNT 105
#define MAX_ATTR_VALUE_COUNT 27

#define DOM_TYPE_INDEX_DIV  0 
#define DOM_TYPE_INDEX_LABEL  1 
#define DOM_TYPE_INDEX_BUTTON  2 
#define DOM_TYPE_INDEX_IMG  3 
#define DOM_TYPE_INDEX_LIST  4 
#define DOM_TYPE_INDEX_QRCODE  5 
#define DOM_TYPE_INDEX_BAR  6 
#define DOM_TYPE_INDEX_TEXTAREA  7 
#define DOM_TYPE_INDEX_LINE  8 
#define DOM_TYPE_INDEX_CHECKBOX  9 
#define DOM_TYPE_INDEX_SWITCH  10 
#define DOM_TYPE_INDEX_SLIDER  11 
#define DOM_TYPE_INDEX_TABVIEW  12 
#define DOM_TYPE_INDEX_TAB  13 
#define DOM_TYPE_INDEX_SPINNER  14 
#define DOM_TYPE_INDEX_ARC  15 
#define DOM_TYPE_INDEX_GIF  16 
#define DOM_TYPE_INDEX_CANVAS  17 
#define DOM_TYPE_INDEX_HZSTROKE  18 
#define DOM_TYPE_INDEX_SPANGROUP  19 
#define DOM_TYPE_INDEX_SPAN  20 
#define DOM_TYPE_INDEX_ROLLER  21 

#define DOM_ATTR_TYPE_INDEX_CLASS  0 
#define DOM_ATTR_TYPE_INDEX_EVENT  1 
#define DOM_ATTR_TYPE_INDEX_WIDTH  2 
#define DOM_ATTR_TYPE_INDEX_HEIGHT  3 
#define DOM_ATTR_TYPE_INDEX_X  4 
#define DOM_ATTR_TYPE_INDEX_Y  5 
#define DOM_ATTR_TYPE_INDEX_ALIGN  6 
#define DOM_ATTR_TYPE_INDEX_ALIGN_TO  7 
#define DOM_ATTR_TYPE_INDEX_ALIGN_POS  8 
#define DOM_ATTR_TYPE_INDEX_SIZE  10 
#define DOM_ATTR_TYPE_INDEX_SHOW  11 
#define DOM_ATTR_TYPE_INDEX_FLAG  12 
#define DOM_ATTR_TYPE_INDEX_ID  13 
#define DOM_ATTR_TYPE_INDEX_SRC  14 
#define DOM_ATTR_TYPE_INDEX_OFFSET_X  15 
#define DOM_ATTR_TYPE_INDEX_OFFSET_Y  16 
#define DOM_ATTR_TYPE_INDEX_ZOOM  17 
#define DOM_ATTR_TYPE_INDEX_ANGLE  18 
#define DOM_ATTR_TYPE_INDEX_PIVOT  19 
#define DOM_ATTR_TYPE_INDEX_ANTIALIAS  20 
#define DOM_ATTR_TYPE_INDEX_SIZE_MODE  21 
#define DOM_ATTR_TYPE_INDEX_TEXT  22 
#define DOM_ATTR_TYPE_INDEX_RECOLOR  23 
#define DOM_ATTR_TYPE_INDEX_LONG_MODE  24 
#define DOM_ATTR_TYPE_INDEX_BTN_LIST  25 
#define DOM_ATTR_TYPE_INDEX_LIST_BTN_CLASS  26 
#define DOM_ATTR_TYPE_INDEX_VALUE  27 
#define DOM_ATTR_TYPE_INDEX_MAX_VALUE  28 
#define DOM_ATTR_TYPE_INDEX_TEXTAREA_TEXT  29 
#define DOM_ATTR_TYPE_INDEX_ONE_LINE  30 
#define DOM_ATTR_TYPE_INDEX_PASSWORD_MODE  31 
#define DOM_ATTR_TYPE_INDEX_ACCEPTED_CHARS  32 
#define DOM_ATTR_TYPE_INDEX_MAX_LENGTH  33 
#define DOM_ATTR_TYPE_INDEX_POINTS  34 
#define DOM_ATTR_TYPE_INDEX_CENTER  35 
#define DOM_ATTR_TYPE_INDEX_SCROLLBAR_MODE  36 
#define DOM_ATTR_TYPE_INDEX_SYMBOL  37 
#define DOM_ATTR_TYPE_INDEX_STATE  38 
#define DOM_ATTR_TYPE_INDEX_CURSOR_POS  39 
#define DOM_ATTR_TYPE_INDEX_LAYOUT  40 
#define DOM_ATTR_TYPE_INDEX_GRID_CELL  41 
#define DOM_ATTR_TYPE_INDEX_GRID_COLUMN_DSC_ARRAY  42 
#define DOM_ATTR_TYPE_INDEX_GRID_ROW_DSC_ARRAY  43 
#define DOM_ATTR_TYPE_INDEX_GRIDNAV  44 
#define DOM_ATTR_TYPE_INDEX_CHECKBOX_TEXT  45 
#define DOM_ATTR_TYPE_INDEX_SWITCH_VALUE  46 
#define DOM_ATTR_TYPE_INDEX_FOCUS  47 
#define DOM_ATTR_TYPE_INDEX_FOCUS_KEY  48 
#define DOM_ATTR_TYPE_INDEX_GROUP_FOCUS  49 
#define DOM_ATTR_TYPE_INDEX_SLIDER_MODE  50 
#define DOM_ATTR_TYPE_INDEX_SLIDER_VALUE  51 
#define DOM_ATTR_TYPE_INDEX_SLIDER_MAX_VALUE  52 
#define DOM_ATTR_TYPE_INDEX_SLIDER_GRIDNAV  53 
#define DOM_ATTR_TYPE_INDEX_GRIDNAV_FOCUS  54 
#define DOM_ATTR_TYPE_INDEX_CLEAR_FLAG  55 
#define DOM_ATTR_TYPE_INDEX_CLEAR_STATE  56 
#define DOM_ATTR_TYPE_INDEX_UPDATE_LAYOUT  57 
#define DOM_ATTR_TYPE_INDEX_SCROLL_TO_X  58 
#define DOM_ATTR_TYPE_INDEX_SCROLL_TO_Y  59 
#define DOM_ATTR_TYPE_INDEX_SCROLL_TO_VIEW  60 
#define DOM_ATTR_TYPE_INDEX_CACHE  61 
#define DOM_ATTR_TYPE_INDEX_TAB_POS  62 
#define DOM_ATTR_TYPE_INDEX_TAB_SIZE  63 
#define DOM_ATTR_TYPE_INDEX_SHOW_TAB_BTNS  64 
#define DOM_ATTR_TYPE_INDEX_ACT  65 
#define DOM_ATTR_TYPE_INDEX_NAME  66 
#define DOM_ATTR_TYPE_INDEX_SCROLL_ANIM  67 
#define DOM_ATTR_TYPE_INDEX_SPIN_TIME  68 
#define DOM_ATTR_TYPE_INDEX_ARC_LENGTH  69 
#define DOM_ATTR_TYPE_INDEX_FG_COLOR  70 
#define DOM_ATTR_TYPE_INDEX_BG_COLOR  71 
#define DOM_ATTR_TYPE_INDEX_QR_SIZE  72 
#define DOM_ATTR_TYPE_INDEX_DATA  73 
#define DOM_ATTR_TYPE_INDEX_SCROLL_ANIM_TIME  74 
#define DOM_ATTR_TYPE_INDEX_DISABLE_SCROLL  75 
#define DOM_ATTR_TYPE_INDEX_ROTATION  76 
#define DOM_ATTR_TYPE_INDEX_ARC_VALUE  77 
#define DOM_ATTR_TYPE_INDEX_START_ANGLE  78 
#define DOM_ATTR_TYPE_INDEX_END_ANGLE  79 
#define DOM_ATTR_TYPE_INDEX_ANGLES  80 
#define DOM_ATTR_TYPE_INDEX_BG_START_ANGLE  81 
#define DOM_ATTR_TYPE_INDEX_BG_END_ANGLE  82 
#define DOM_ATTR_TYPE_INDEX_BG_ANGLES  83 
#define DOM_ATTR_TYPE_INDEX_ARC_MODE  84 
#define DOM_ATTR_TYPE_INDEX_RANGE  85 
#define DOM_ATTR_TYPE_INDEX_CHANGE_RATE  86 
#define DOM_ATTR_TYPE_INDEX_REMOVE_STYLE  87 
#define DOM_ATTR_TYPE_INDEX_GIF_SRC  88 
#define DOM_ATTR_TYPE_INDEX_RESTART  89 
#define DOM_ATTR_TYPE_INDEX_GIF_CACHE  90 
#define DOM_ATTR_TYPE_INDEX_GIF_ZOOM  91 
#define DOM_ATTR_TYPE_INDEX_PAUSE  92 
#define DOM_ATTR_TYPE_INDEX_INS_TEXT  93 
#define DOM_ATTR_TYPE_INDEX_EXT_CLICK_AREA  94 
#define DOM_ATTR_TYPE_INDEX_CANVAS_SIZE  95 
#define DOM_ATTR_TYPE_INDEX_LEFT_VALUE  96 
#define DOM_ATTR_TYPE_INDEX_CONTENT_WIDTH  97 
#define DOM_ATTR_TYPE_INDEX_CONTENT_HEIGHT  98 
#define DOM_ATTR_TYPE_INDEX_SCROLL_TO_VIEW_RECURSIVE  99 
#define DOM_ATTR_TYPE_INDEX_HZSTROKE_SRC  100 
#define DOM_ATTR_TYPE_INDEX_HZSTROKE_CACHE  101 
#define DOM_ATTR_TYPE_INDEX_REPEAT  102 
#define DOM_ATTR_TYPE_INDEX_STATUS  103 
#define DOM_ATTR_TYPE_INDEX_SPEED  104 
#define DOM_ATTR_TYPE_INDEX_LINE_COLOR  105 
#define DOM_ATTR_TYPE_INDEX_STROKE_BG_COLOR  106 
#define DOM_ATTR_TYPE_INDEX_STROKE_COLOR  107 
#define DOM_ATTR_TYPE_INDEX_SCROLL_TOP  108 
#define DOM_ATTR_TYPE_INDEX_SCROLL_BUTTOM  109 
#define DOM_ATTR_TYPE_INDEX_SCROLL_LEFT  110 
#define DOM_ATTR_TYPE_INDEX_SCROLL_RIGHT  111 
#define DOM_ATTR_TYPE_INDEX_SPANGROUP_ALIGN  113 
#define DOM_ATTR_TYPE_INDEX_OVERFLOW  114 
#define DOM_ATTR_TYPE_INDEX_INDENT  115 
#define DOM_ATTR_TYPE_INDEX_SPANGROUP_MODE  116 
#define DOM_ATTR_TYPE_INDEX_SPAN_TEXT  117 
#define DOM_ATTR_TYPE_INDEX_TEXT_COLOR  118 
#define DOM_ATTR_TYPE_INDEX_FONT  119 
#define DOM_ATTR_TYPE_INDEX_CUR_STROKE_COLOR  120 
#define DOM_ATTR_TYPE_INDEX_DISK_CACHE  121 
#define DOM_ATTR_TYPE_INDEX_ADD_TEXT  122 
#define DOM_ATTR_TYPE_INDEX_PLACEHOLDER_TEXT  123 
#define DOM_ATTR_TYPE_INDEX_DEL_CHAR  124 
#define DOM_ATTR_TYPE_INDEX_DEL_CHAR_FORWARD  125 
#define DOM_ATTR_TYPE_INDEX_CURSOR_RIGHT  126 
#define DOM_ATTR_TYPE_INDEX_CURSOR_LEFT  127 
#define DOM_ATTR_TYPE_INDEX_CURSOR_UP  128 
#define DOM_ATTR_TYPE_INDEX_CURSOR_DOWN  129 
#define DOM_ATTR_TYPE_INDEX_CURSOR_CLICK_POS  130 
#define DOM_ATTR_TYPE_INDEX_TEXT_SELECTION  131 
#define DOM_ATTR_TYPE_INDEX_VISIBLE_ROW_COUNT  132 
#define DOM_ATTR_TYPE_INDEX_SELECTED  133 
#define DOM_ATTR_TYPE_INDEX_OPTIONS  134 
#define DOM_ATTR_TYPE_INDEX_DRAG  135 
#define DOM_ATTR_TYPE_INDEX_DISK_CACHE_BIN  136 
#define DOM_ATTR_TYPE_INDEX_ZOOM_WIDTH  137 
#define DOM_ATTR_TYPE_INDEX_VIRTUAL_LIST_DATA  138 
#define DOM_ATTR_TYPE_INDEX_VIRTUAL_LIST_POSITION  139 
#define DOM_ATTR_TYPE_INDEX_VIRTUAL_LIST_FOCUSED_INDEX  140 
#define DOM_ATTR_TYPE_INDEX_VIRTUAL_LIST_FOCUSED_ITEM_DATA  141 
#define DOM_ATTR_TYPE_INDEX_IS_CONTENT_IN_MEM  142 
#define DOM_ATTR_TYPE_INDEX_GIF_IS_CONTENT_IN_MEM  143 
#define DOM_ATTR_TYPE_INDEX_VIRTUAL_LIST_SET_FOCUSED  144 
#define DOM_ATTR_TYPE_INDEX_NAV_LONG_PRESS  145 
#define DOM_ATTR_TYPE_INDEX_SCROLL_SNAP_X  146 
#define DOM_ATTR_TYPE_INDEX_SCROLL_SNAP_Y  147 
#define DOM_ATTR_TYPE_INDEX_OPTIONS_MODE  148 
#define DOM_ATTR_TYPE_INDEX_CIRCULAR_SCROLL  149 
#define DOM_ATTR_TYPE_INDEX_FOCUS_INDEX  150 
#define DOM_ATTR_TYPE_INDEX_LOOP_COUNT  152 
#define DOM_ATTR_TYPE_INDEX_IS_LOAD_MEM  154 
#define DOM_ATTR_TYPE_INDEX_PLACEHOLDER_SRC  155 
#define DOM_ATTR_TYPE_INDEX_INVALIDATE  156 
#define DOM_ATTR_TYPE_INDEX_CHECKED  157 
#define DOM_ATTR_TYPE_INDEX_SCROLLED  158 
#define DOM_ATTR_TYPE_INDEX_DISABLED  159 
#define DOM_ATTR_TYPE_INDEX_PRESSED  160 
#define DOM_ATTR_TYPE_INDEX_KEY_MODE  161 

#define CSS_ATTR_TYPE_INDEX_WIDTH  0 
#define CSS_ATTR_TYPE_INDEX_MIN_WIDTH  1 
#define CSS_ATTR_TYPE_INDEX_MAX_WIDTH  2 
#define CSS_ATTR_TYPE_INDEX_HEIGHT  3 
#define CSS_ATTR_TYPE_INDEX_MIN_HEIGHT  4 
#define CSS_ATTR_TYPE_INDEX_MAX_HEIGHT  5 
#define CSS_ATTR_TYPE_INDEX_X  6 
#define CSS_ATTR_TYPE_INDEX_Y  7 
#define CSS_ATTR_TYPE_INDEX_ALIGN  8 
#define CSS_ATTR_TYPE_INDEX_TRANSFORM_WIDTH  9 
#define CSS_ATTR_TYPE_INDEX_TRANSFORM_HEIGHT  10 
#define CSS_ATTR_TYPE_INDEX_TRANSLATE_X  11 
#define CSS_ATTR_TYPE_INDEX_TRANSLATE_Y  12 
#define CSS_ATTR_TYPE_INDEX_TRANSFORM_ZOOM  13 
#define CSS_ATTR_TYPE_INDEX_TRANSFORM_ANGLE  14 
#define CSS_ATTR_TYPE_INDEX_PAD_TOP  15 
#define CSS_ATTR_TYPE_INDEX_PAD_BOTTOM  16 
#define CSS_ATTR_TYPE_INDEX_PAD_LEFT  17 
#define CSS_ATTR_TYPE_INDEX_PAD_RIGHT  18 
#define CSS_ATTR_TYPE_INDEX_PAD_ROW  19 
#define CSS_ATTR_TYPE_INDEX_PAD_COLUMN  20 
#define CSS_ATTR_TYPE_INDEX_BG_COLOR  21 
#define CSS_ATTR_TYPE_INDEX_BG_OPA  22 
#define CSS_ATTR_TYPE_INDEX_BG_GRAD_COLOR  23 
#define CSS_ATTR_TYPE_INDEX_BG_GRAD_DIR  24 
#define CSS_ATTR_TYPE_INDEX_BG_MAIN_STOP  25 
#define CSS_ATTR_TYPE_INDEX_BG_GRAD_STOP  26 
#define CSS_ATTR_TYPE_INDEX_BG_GRAD  27 
#define CSS_ATTR_TYPE_INDEX_BG_DITHER_MODE  28 
#define CSS_ATTR_TYPE_INDEX_BG_IMG_SRC  29 
#define CSS_ATTR_TYPE_INDEX_BG_IMG_OPA  30 
#define CSS_ATTR_TYPE_INDEX_BG_IMG_RECOLOR  31 
#define CSS_ATTR_TYPE_INDEX_BG_IMG_RECOLOR_OPA  32 
#define CSS_ATTR_TYPE_INDEX_BG_IMG_TILED  33 
#define CSS_ATTR_TYPE_INDEX_BORDER_COLOR  34 
#define CSS_ATTR_TYPE_INDEX_BORDER_OPA  35 
#define CSS_ATTR_TYPE_INDEX_BORDER_WIDTH  36 
#define CSS_ATTR_TYPE_INDEX_BORDER_SIDE  37 
#define CSS_ATTR_TYPE_INDEX_BORDER_POST  38 
#define CSS_ATTR_TYPE_INDEX_OUTLINE_WIDTH  39 
#define CSS_ATTR_TYPE_INDEX_OUTLINE_PAD  40 
#define CSS_ATTR_TYPE_INDEX_OUTLINE_COLOR  41 
#define CSS_ATTR_TYPE_INDEX_OUTLINE_OPA  43 
#define CSS_ATTR_TYPE_INDEX_SHADOW_WIDTH  44 
#define CSS_ATTR_TYPE_INDEX_SHADOW_OFS_X  45 
#define CSS_ATTR_TYPE_INDEX_SHADOW_OFS_Y  46 
#define CSS_ATTR_TYPE_INDEX_SHADOW_SPREAD  47 
#define CSS_ATTR_TYPE_INDEX_SHADOW_COLOR  48 
#define CSS_ATTR_TYPE_INDEX_SHADOW_OPA  49 
#define CSS_ATTR_TYPE_INDEX_LINE_DASH_WIDTH  54 
#define CSS_ATTR_TYPE_INDEX_LINE_DASH_GAP  55 
#define CSS_ATTR_TYPE_INDEX_LINE_ROUNDED  56 
#define CSS_ATTR_TYPE_INDEX_ARC_WIDTH  59 
#define CSS_ATTR_TYPE_INDEX_ARC_ROUNDED  60 
#define CSS_ATTR_TYPE_INDEX_ARC_COLOR  61 
#define CSS_ATTR_TYPE_INDEX_ARC_IMG_SRC  62 
#define CSS_ATTR_TYPE_INDEX_TEXT_OPA  64 
#define CSS_ATTR_TYPE_INDEX_FONT  65 
#define CSS_ATTR_TYPE_INDEX_TEXT_LETTER_SPACE  66 
#define CSS_ATTR_TYPE_INDEX_TEXT_LINE_SPACE  67 
#define CSS_ATTR_TYPE_INDEX_TEXT_DECOR  68 
#define CSS_ATTR_TYPE_INDEX_TEXT_ALIGN  69 
#define CSS_ATTR_TYPE_INDEX_RADIUS  70 
#define CSS_ATTR_TYPE_INDEX_CLIP_CORNER  71 
#define CSS_ATTR_TYPE_INDEX_COLOR_FILTER_DSC  73 
#define CSS_ATTR_TYPE_INDEX_COLOR_FILTER_OPA  74 
#define CSS_ATTR_TYPE_INDEX_ANIM_TIME  75 
#define CSS_ATTR_TYPE_INDEX_ANIM_SPEED  76 
#define CSS_ATTR_TYPE_INDEX_BLEND_MODE  77 
#define CSS_ATTR_TYPE_INDEX_LAYOUT  78 
#define CSS_ATTR_TYPE_INDEX_FLEX_FLOW  79 
#define CSS_ATTR_TYPE_INDEX_FLEX_MAIN_PLACE  80 
#define CSS_ATTR_TYPE_INDEX_CROSS_PLACE  81 
#define CSS_ATTR_TYPE_INDEX_FLEX_TRACK_PLACE  82 
#define CSS_ATTR_TYPE_INDEX_FLEX_GROW  83 
#define CSS_ATTR_TYPE_INDEX_JUSTIFY_CONTENT  85 
#define CSS_ATTR_TYPE_INDEX_ALIGN_ITEMS  86 
#define CSS_ATTR_TYPE_INDEX_ALIGN_CONTENT  87 
#define CSS_ATTR_TYPE_INDEX_DISPLAY  89 
#define CSS_ATTR_TYPE_INDEX_BACKGROUND_COLOR  90 
#define CSS_ATTR_TYPE_INDEX_PADDING_TOP  91 
#define CSS_ATTR_TYPE_INDEX_PADDING_BOTTOM  92 
#define CSS_ATTR_TYPE_INDEX_PADDING_LEFT  93 
#define CSS_ATTR_TYPE_INDEX_PADDING_RIGHT  94 
#define CSS_ATTR_TYPE_INDEX_BACKGROUND  99 
#define CSS_ATTR_TYPE_INDEX_BASE_DIR  100 
#define CSS_ATTR_TYPE_INDEX_PAD_ALL  101 
#define CSS_ATTR_TYPE_INDEX_TRANSFORM_PIVOT_X  102 
#define CSS_ATTR_TYPE_INDEX_TRANSFORM_PIVOT_Y  103 
#define CSS_ATTR_TYPE_INDEX_ARC_OPA  104 


int get_state_lv_value(const char * html);
int get_flag_lv_value(const char * html);
int get_align_lv_value(const char * html);
int get_flex_align_lv_value(const char * html);
int get_flex_flow_lv_value(const char * html);
int get_label_long_mode_lv_value(const char * html);
int get_layout_lv_value(const char * html);
int get_grad_dir_lv_value(const char * html);
int get_bg_grad_lv_value(const char * html);
int get_dither_lv_value(const char * html);
int get_bool_lv_value(const char * html);
int get_text_decor_lv_value(const char * html);
int get_text_align_lv_value(const char * html);
int get_blend_mode_lv_value(const char * html);
int get_size_mode_lv_value(const char * html);
int get_scrollbar_mode_lv_value(const char * html);
int get_base_dir_lv_value(const char * html);
int get_event_lv_value(const char * html);
int get_part_lv_value(const char * html);
int get_grid_align_lv_value(const char * html);
int get_dir_lv_value(const char * html);
int get_slider_mode_lv_value(const char * html);
int get_gridnav_flag_lv_value(const char * html);
int get_border_size_lv_value(const char * html);
int get_arc_mode_lv_value(const char * html);
int get_span_overflow_lv_value(const char * html);
int get_span_mode_lv_value(const char * html);


typedef struct {
    char *name;
    int index;
} guAttrLVValue_t;

typedef struct {
    char *name;
    guAttrLVValue_t *map;
    int count;
} guAttrLVMap_t;

extern guFuncPoint_t gCssStyleSetFuncMap[MAX_CSS_STYLE_MAP_COUNT];
extern guFuncPoint_t gLocalStyleSetFuncMap[MAX_CSS_STYLE_MAP_COUNT];
extern guFuncPoint_t gDomCreateFuncMap[MAX_DOM_COUNT];
extern guFuncPoint_t gDomSetAttrFuncMap[MAX_DOM_ATTR_COUNT];
extern guFuncPoint_t gDomGetAttrFuncMap[MAX_DOM_ATTR_COUNT];

extern int getDomTypeIndex(const char *domname);
extern int getDomAttrIndex(int DomTypeIndex, char *attrname);
extern int getStyleTypeIndex(const char *name);
extern char *getAttrValueNameByIndex(int DomTypeIndex, int AttrValueIndex);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*GU_CSS_H*/
