/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef XRECORD_H
#define XRECORD_H

#include "CdxKeyedVector.h"
#include "CaptureControl.h"

#define AUDIO_INPUT (1)
#define VIDEO_INPUT (0)

typedef struct RecoderContext XRecord;

typedef enum XRECODER_AUDIO_ENCODE_TYPE
{
    XRECODER_AUDIO_ENCODE_AMR_TYPE,
    XRECODER_AUDIO_ENCODE_PCM_TYPE,
    XRECODER_AUDIO_ENCODE_MP3_TYPE,
    XRECODER_AUDIO_ENCODE_AAC_TYPE
} XRECODER_AUDIO_ENCODE_TYPE;

typedef enum
{
    XRECODER_STATE_INIT,
    XRECODER_STATE_PREPARED,
    XRECODER_STATE_STARTED,
    XRECODER_STATE_STOPED,
    XRECODER_STATE_DESTROYED,
} XRECODER_STATE;

typedef struct XRecordConfig
{
    int                 nSamplerate;   //
    int                 nChan;         //pcm chan 1:mon 2:stereo
    int                 nBitrate;      //
    int                 nSamplerBits;  //only for 16bits
}XRecordConfig;

XRecord* XRecordCreate();

int XRecordSetDataDstUrl(XRecord* p,
                            const char* pUrl,
                            void* arg,
                            const CdxKeyedVectorT* pHeaders);

int XRecordDestroy(XRecord* p);

void XRecordSetAudioCap(XRecord* p, const CaptureCtrl* audioSrc);

int XRecordSetAudioEncodeType(XRecord* p, XRECODER_AUDIO_ENCODE_TYPE type, XRecordConfig *config);

int XRecordPrepare(XRecord* p);

int XRecordStart(XRecord* p);

int XRecordStop(XRecord* p);

#endif /* XRECORD_H */