/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _SUNXI_ANTI_COPY_BOARD_H_
#define _SUNXI_ANTI_COPY_BOARD_H_

/* SID CONFIGURATION */
#ifdef CONFIG_ARCH_SUN20IW2
/* get from sid spec */
/* write protect */
#define EFUSE_WRITE_PROTECT	(0x48)
/* read  protect */
#define EFUSE_READ_PROTECT	(0x4C)
#define SSK_WRITE_PROTECT_FLAG	(12)
#define SSK_READ_PROTECT_FLAG	(12)

#define SSK_KEYLEN		(16)	// Bytes
#endif

#define PLAINTEXT_PATH "/data/plaintext"
#define CIPHERTEXT_PATH "/data/ciphertext"
#define FILE_LENGTH (128)

/* CE CONFIGUREATION */
#define AES_MODE_ECB		(0)
#define AES_DIR_DECRYPT		(1)

/* ACB return value */
#define ACB_VERIFY_RET_OK			(0)
#define ACB_VERIFY_RET_NO_SSK_ERR		(-1)
#define ACB_VERIFY_RET_NO_PLAIN_CIPHER_ERR	(-2)
#define ACB_VERIFY_RET_VERIFY_ERR		(-3)
#define ACB_VERIFY_RET_NO_ALL_ERR		(-4)
#define ACB_VERIFY_RET_MALLOC_ERR		(-5)
#define ACB_VERIFY_RET_READ_DATA_ERR		(-6)

#define ACB_BURN_RET_OK				(0)
#define ACB_BURN_RET_ARG_ERR			(-1)
#define ACB_BURN_RET_MALLOC_ERR			(-2)
#define ACB_BURN_RET_SSK_WRITE_ERR		(-3)
#define ACB_BURN_RET_SSK_CMP_ERR		(-4)
#define ACB_BURN_RET_SSK_SET_RB_FBD_ERR		(-5)
#define ACB_BURN_RET_NO_PLAINTEXT_ERR		(-6)
#define ACB_BURN_RET_NO_CIPHERTEXT_ERR		(-7)
#define ACB_BURN_RET_PLAINTEXT_SIZE_ERR		(-8)
#define ACB_BURN_RET_CIPHERTEXT_SIZE_ERR	(-9)
#define ACB_BURN_RET_VERIFY_ERR			(-10)

int acb_verify(char *plain_path, char *cipher_path);

#endif
