/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __AACTD_DRC_HW_H__
#define __AACTD_DRC_HW_H__

#include "aactd/communicate.h"

#define MAX_DRC_3_BAND_REG_NUM (78)

#define MAX_DRC_1_BAND_REG_NUM (26)


#define DRC1B_REG_MIN 	0x600
#define DRC1B_REG_MAX	0x660
#define DRC3B_REG_MIN 	0x700
#define DRC3B_REG_MAX	0x834

int drc_hw_local_init(void);
int drc_hw_local_release(void);

int drc_hw_write_com_to_local(const struct aactd_com *com);

#if defined(CONFIG_ARCH_SUN8IW18) || defined(CONFIG_ARCH_SUN8IW19) || defined(CONFIG_ARCH_SUN8IW20)

#define drchw_writel(value,reg)   (*(volatile uint32_t *)(reg) = (value))

#if defined(CONFIG_ARCH_SUN8IW18) || defined(CONFIG_ARCH_SUN8IW19)
#define DRC_HW_REG_BASE_ADDR 0x05096000

#define DAC_DRC_REG_MIN 0xF0
#define DAC_DRC_REG_MAX	0x1B0

#define ADC_DRC_REG_MIN 0xF8
#define ADC_DRC_REG_MAX	0x2B0

#endif

#ifdef CONFIG_ARCH_SUN8IW20
#define DRC_HW_REG_BASE_ADDR 0x02030000

#define DAC_DRC_REG_MIN 0xF0
#define DAC_DRC_REG_MAX	0x1B0

#define ADC_DRC_REG_MIN 0xF8
#define ADC_DRC_REG_MAX	0x2B0

#endif

#ifndef DRC_HW_REG_BASE_ADDR
#error "not define DRC_HW_REG_BASE_ADDR"
#endif

#endif

#endif /* ifndef __AACTD_DRC_HW_H__ */
