/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __RTC_DEBUG_H
#define __RTC_DEBUG_H

#include <stdint.h>
#include "platform.h"
#include "hal_prcm.h"

/* standby progress record */
/* macro record */
#define REC_SSTANDBY     (0xf1f10000)
#define REC_NSTANDBY     (0xf2f20000)
#define REC_ESTANDBY     (0xf3f30000)
#define REC_FAKEPOWEROFF (0xf4f40000)
#define REC_TSTANDBY     (0xf5f50000)
#define REC_AUDIO        (0xf6f60000)

/* micro record */
#define REC_COPY_DONE     (0x0000)
#define REC_ENTER         (0x1000)
#define REC_BEFORE_INIT   (0x2000)
#define REC_ENTER_INIT    (0x3000)
#define REC_AFTER_INIT    (0x4000)
#define REC_WAIT_WAKEUP   (0x5000)
#define REC_BEFORE_EXIT   (0x6000)
#define REC_ENTER_EXIT    (0x7000)
#define REC_AFTER_EXIT    (0x8000)
#define REC_DRAM_DBG      (0x9000)
#define REC_SHUTDOWN      (0xa000)
#define REC_HOTPULG       (0xb000)
#define REC_CPUX_RESUME   (0xc000)
#define REC_DEBUG         (0xd000)
#define REC_CPUS_LOOP     (0xe000)
#define REC_CPUS_WAKEUP   (0xf000)

/* audio debug micro */
#define REC_AUDIO_CORE       (0x0000)
#define REC_AUDIO_PCM        (0x1000)
#define REC_AUDIO_MIXER      (0x2000)
#define REC_AUDIO_DEBUG      (0x3000)
#define REC_AUDIO_COMPONENT  (0x4000)
#define REC_AUDIO_COMMON     (0x5000)
#define REC_AUDIO_STANDBY    (0x6000)

#endif
