/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __FLASH_CONTROLLER_REG__
#define __FLASH_CONTROLLER_REG__

#include <sunxi_hal_common.h>

#define fc_readb(addr) hal_readb(addr)
#define fc_readl(addr) hal_readl(addr)

#define fc_writeb(data, addr) hal_writeb(data, addr)
#define fc_writel(data, addr) hal_writel(data, addr)

/* flash controller register offset */
#define MEM_CTRL_REG_OFF 0x00
#define QSPI_CONTROLLER_CFG_REG_OFF 0x04

#define MEM_MAP_MODE_CACHE_CFG_REG_OFF 0x08
#define MEM_MAP_MODE_READ_PROTOCOL_REG_OFF 0x10
#define MEM_MAP_MODE_WRITE_PROTOCOL_REG_OFF 0x14
#define MEM_MAP_MODE_DUMMY_DATA_HIGH_REG_OFF 0x18
#define MEM_MAP_MODE_DUMMY_DATA_LOW_REG_OFF 0x1C

#define INDIRECT_MODE_PROTOCOL_CFG_REG_OFF 0x2C
#define INDIRECT_MODE_FLASH_DATA_ADDR_REG_OFF 0x30
#define INDIRECT_MODE_DUMMY_DATA_HIGH_REG_OFF 0x34
#define INDIRECT_MODE_DUMMY_DATA_LOW_REG_OFF 0x38
#define INDIRECT_MODE_IO_LATENCY_REG_OFF 0x3C
#define INDIRECT_MODE_WRITE_PAYLOAD_LEN_REG_OFF 0x40
#define INDIRECT_MODE_READ_PAYLOAD_LEN_REG_OFF 0x44
#define INDIRECT_MODE_START_SEND_REG_OFF 0x48
#define FIFO_LEVEL_CFG_REG_OFF 0x4C
#define FIFO_STATUS_REG_OFF 0x50
#define INT_CTRL_REG_OFF 0x54
#define INT_STATUS_REG_OFF 0x58

#define MEM_MAP0_START_ADDR_REG_OFF 0x80
#define MEM_MAP0_END_ADDR_REG_OFF 0x84
#define MEM_MAP0_OFFSET_REG_OFF 0x88

#define MEM_MAP1_START_ADDR_REG_OFF 0x90
#define MEM_MAP1_END_ADDR_REG_OFF 0x94
#define MEM_MAP1_OFFSET_REG_OFF 0x98

#define MEM_MAP2_START_ADDR_REG_OFF 0xA0
#define MEM_MAP2_END_ADDR_REG_OFF 0xA4
#define MEM_MAP2_OFFSET_REG_OFF 0xA8

#define MEM_MAP3_START_ADDR_REG_OFF 0xB0
#define MEM_MAP3_END_ADDR_REG_OFF 0xB4
#define MEM_MAP3_OFFSET_REG_OFF 0xB8

#define MEM_MAP4_START_ADDR_REG_OFF 0xC0
#define MEM_MAP4_END_ADDR_REG_OFF 0xC4
#define MEM_MAP4_OFFSET_REG_OFF 0xC8

#define MEM_MAP5_START_ADDR_REG_OFF 0xD0
#define MEM_MAP5_END_ADDR_REG_OFF 0xD4
#define MEM_MAP5_OFFSET_REG_OFF 0xD8


#define INDIRECT_MODE_WRITE_DATA_REG_OFF 0x100
#define INDIRECT_MODE_READ_DATA_REG_OFF 0x200


/* MEM_CTRL_REG */
#define FLASH_ADDR_SIZE_MODE_SHIFT 30
#define FLASH_ADDR_SIZE_MODE_MASK (0x3 << FLASH_ADDR_SIZE_MODE_SHIFT)

#define IO1_OUTPUT_WHEN_IDLE_SHIFT 28
#define IO1_OUTPUT_WHEN_IDLE_BIT_MASK (0x3 << IO1_OUTPUT_WHEN_IDLE_SHIFT)

#define IO2_OUTPUT_WHEN_IDLE_SHIFT 26
#define IO2_OUTPUT_WHEN_IDLE_BIT_MASK (0x3 << IO2_OUTPUT_WHEN_IDLE_SHIFT)

#define IO3_OUTPUT_WHEN_IDLE_SHIFT 24
#define IO3_OUTPUT_WHEN_IDLE_BIT_MASK (0x3 << IO3_OUTPUT_WHEN_IDLE_SHIFT)

#define INVALIDATE_CACHE_ENABLE_SHIFT 16
#define INVALIDATE_CACHE_ENABLE_MASK (0x1 << INVALIDATE_CACHE_ENABLE_SHIFT)

#define RESET_TX_FIFO_SHIFT 6
#define RESET_TX_FIFO_MASK (0x1 << RESET_TX_FIFO_SHIFT)

#define RESET_RX_FIFO_SHIFT 5
#define RESET_RX_FIFO_MASK (0x1 << RESET_RX_FIFO_SHIFT)

#define BUS_ARBITRATION_ENABLE_SHIFT 4
#define BUS_ARBITRATION_ENABLE_MASK (0x1 << BUS_ARBITRATION_ENABLE_SHIFT)

#define WARP_AROUND_MODE_ENABLE_SHIFT 3
#define WARP_AROUNDMODE_ENABLE_MASK (0x1 << WARP_AROUND_MODE_ENABLE_SHIFT)

#define CONTINUOUS_READ_MODE_ENABLE_SHIFT 2
#define CONTINUOUS_READ_MODE_ENABLE_MASK (0x1 << CONTINUOUS_READ_MODE_ENABLE_SHIFT)

#define MEM_MAP_MODE_ENABLE_SHIFT 0
#define MEM_MAP_MODE_ENABLE_MASK (0x1 << MEM_MAP_MODE_ENABLE_SHIFT)

/* QSPI_CONTROLLER_CFG_REG */
#define RX_SAMPLE_DELAY_SHIFT 12
#define RX_SAMPLE_DELAY_BIT_MASK (0x3 << RX_SAMPLE_DELAY_SHIFT)

#define SPI_CS_POLARITY_SHIFT 8
#define SPI_CS_POLARITY_BIT_MASK (0x1 << SPI_CS_POLARITY_SHIFT)

#define SPI_RX_ENDIAN_SHIFT 4
#define SPI_RX_ENDIAN_BIT_MASK (0x1 << SPI_RX_ENDIAN_SHIFT)

#define SPI_CLK_POLARITY_SHIFT 1
#define SPI_CLK_POLARITY_BIT_MASK (0x1 << SPI_CLK_POLARITY_SHIFT)

#define SPI_CLK_PHASE_SHIFT 0
#define SPI_CLK_PHASE_BIT_MASK (0x1 << SPI_CLK_PHASE_SHIFT)

/* MEM_MAP_MODE_CACHE_CFG_REG */
#define READ_CACHE_LINE_SIZE_SHIFT 0
#define READ_CACHE_LINE_SIZE_BIT_MASK (0x3 << READ_CACHE_LINE_SIZE_SHIFT)


/* MEM_MAP_MODE_READ_PROTOCOL_REG */
#define MEM_MAP_MODE_CMD_DATA_SHIFT (24)
#define MEM_MAP_MODE_CMD_DATA_MASK (0xFF << MEM_MAP_MODE_CMD_DATA_SHIFT)

#define MEM_MAP_MODE_CMD_LINES_SHIFT (20)
#define MEM_MAP_MODE_CMD_LINES_BIT_MASK (0x7U << MEM_MAP_MODE_CMD_LINES_SHIFT)

#define MEM_MAP_MODE_ADDR_LINES_SHIFT (16)
#define MEM_MAP_MODE_ADDR_LINES_BIT_MASK (0x7U << MEM_MAP_MODE_ADDR_LINES_SHIFT)

#define MEM_MAP_MODE_DUMMY_FIELD_LINES_SHIFT (12)
#define MEM_MAP_MODE_DUMMY_FIELD_LINES_BIT_MASK (0x7U << MEM_MAP_MODE_DUMMY_FIELD_LINES_SHIFT)

#define MEM_MAP_MODE_DUMMY_FIELD_LEN_SHIFT (4)
#define MEM_MAP_MODE_DUMMY_FIELD_LEN_BIT_MASK (0x7FU << MEM_MAP_MODE_DUMMY_FIELD_LEN_SHIFT)

#define MEM_MAP_MODE_PAYLOAD_LINES_SHIFT (0)
#define MEM_MAP_MODE_PAYLOAD_LINES_BIT_MASK (0x7U << MEM_MAP_MODE_PAYLOAD_LINES_SHIFT)


/* INDIRECT_MODE_PROTOCOL_CFG  */
#define INDIRECT_MODE_CMD_DATA_SHIFT (24)
#define INDIRECT_MODE_CMD_DATA_MASK (0xFF << INDIRECT_MODE_CMD_DATA_SHIFT)

#define INDIRECT_MODE_CMD_LINES_SHIFT (20)
#define INDIRECT_MODE_CMD_LINES_BIT_MASK (0x7U << INDIRECT_MODE_CMD_LINES_SHIFT)

#define INDIRECT_MODE_ADDR_LINES_SHIFT (16)
#define INDIRECT_MODE_ADDR_LINES_BIT_MASK (0x7U << INDIRECT_MODE_ADDR_LINES_SHIFT)

#define INDIRECT_MODE_DUMMY_FIELD_LINES_SHIFT (12)
#define INDIRECT_MODE_DUMMY_FIELD_LINES_BIT_MASK (0x7U << INDIRECT_MODE_DUMMY_FIELD_LINES_SHIFT)

#define INDIRECT_MODE_DUMMY_FIELD_LEN_SHIFT (4)
#define INDIRECT_MODE_DUMMY_FIELD_LEN_BIT_MASK (0x7FU << INDIRECT_MODE_DUMMY_FIELD_LEN_SHIFT)

#define INDIRECT_MODE_PAYLOAD_LINES_SHIFT (0)
#define INDIRECT_MODE_PAYLOAD_LINES_BIT_MASK (0x7U << INDIRECT_MODE_PAYLOAD_LINES_SHIFT)


/* START_SEND_REG */
#define START_SEND_SHIFT                        0
#define START_SEND_MASK                         (0x1U << START_SEND_SHIFT)

/* FIFO_STATUS_REG */
#define WRITE_FIFO_DATA_CNT_SHIFT 8
#define WRITE_FIFO_DATA_CNT_MASK (0xFF << WRITE_FIFO_DATA_CNT_SHIFT)

#define READ_FIFO_DATA_CNT_SHIFT 0
#define READ_FIFO_DATA_CNT_MASK (0xFF << READ_FIFO_DATA_CNT_SHIFT)

/* MEM_MAPx_START_ADDR_REG_OFF */
#define MEM_MAP_CFG_REG_ADDR_INTERVAL 0x10
#define MEM_MAP_ADDR_SHIFT 0
#define MEM_MAP_ADDR_MASK (0x3FFFFFF0 << 0)

/* MEM_MAPx_OFFSET_REG_OFF */
#define MEM_MAP_ENABLE_SHIFT 31
#define MEM_MAP_ENABLE_MASK (0x1 << MEM_MAP_ENABLE_SHIFT)
#define MEM_MAP_OFFSET_SHIFT 0
#define MEM_MAP_OFFSET_MASK (0x7FFFFFFF << MEM_MAP_OFFSET_SHIFT)


#endif /* __FLASH_CONTROLLER_REG__ */
