obj-y += src/main.o
obj-y += src/assert.o
obj-y += src/hooks.o
obj-y += src/alsa_config.o
obj-y += src/card_default.o

obj-$(CONFIG_PROJECT_DEMO_TEST_QUEUE)  += src/main_blinky.o

CFLAGS += -I $(BASE)/drivers/drv/wireless/xradio/adapter/
