# Allwinner Audio Driver Framework Core
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_FRAMEWORK_CORE) += sunxi_adf_core.o

# Allwinner Audio Driver Framework Component
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_FRAMEWORK_COMPONENT) += sunxi_adf_component.o

# Allwinner Audio Driver Framework dai
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_FRAMEWORK_DAI) += sunxi_adf_dai.o

# Allwinner Audio Driver Framework pcm
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_FRAMEWORK_PCM) += sunxi_adf_pcm.o

