ifeq ($(CONFIG_COMPONENTS_AW_EFPG),y)
obj-y += efpg_efuse.o
obj-y += efpg.o
#obj-y += efpg_frame.o
obj-y += efpg_test.o
endif

#CFLAGS += -I components/thirdparty/console
#CFLAGS += -I components/thirdparty/ulog/syslog
