/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _PM_TESTLEVEL_H_
#define _PM_TESTLEVEL_H_

#ifdef CONFIG_ARCH_SUN20IW2
#define GPRCM_SYS_PRIV_REG2		(0x40050208)
#define GPRCM_SYS_PRIV_REG4		(0x40050210)
#define GPRCM_SYS_PRIV_REG5		(0x40050214)
#define GPRCM_SYS_PRIV_REG6		(0x40050218)

#define PM_STANDBY_STAGE_M33_REC_REG	(GPRCM_SYS_PRIV_REG6)
#define PM_STANDBY_STAGE_C906_REC_REG	(GPRCM_SYS_PRIV_REG5)
#define PM_STANDBY_STAGE_DSP_REC_REG	(GPRCM_SYS_PRIV_REG4)
#define PM_STANDBY_STAGE_PSRAM_REC_REG	(GPRCM_SYS_PRIV_REG2)

#define LSPSRAM_CRC_FAIL_FLAG		(0xf3f3ff01)
#define LSPSRAM_RESUME_FAIL_FLAG	(0xf3f3ff02)
#define HSPSRAM_CRC_FAIL_FLAG		(0xf3f3ee01)
#endif

#define PM_TEST_RECORDING_ENTER		(0xfcfc0000)

typedef enum suspend_testlevel {
	PM_SUSPEND_TEST_NONE = 0,
	PM_SUSPEND_TEST_FREEZER,
	PM_SUSPEND_TEST_DEVICE,
	PM_SUSPEND_TEST_PLATFORM,
	PM_SUSPEND_TEST_CPU,

	PM_SUSPEND_TEST_MAX,
	PM_SUSPEND_TEST_BASE = PM_SUSPEND_TEST_NONE,
} suspend_testlevel_t;

#define pm_suspend_testlevel_valid(_t) \
	((_t) >= PM_SUSPEND_TEST_BASE && (_t) < PM_SUSPEND_TEST_MAX)


int pm_suspend_test(suspend_testlevel_t level);
int pm_suspend_test_set(suspend_testlevel_t level);

/* PM standby test record */
int pm_test_standby_recording(void);
#ifdef CONFIG_COMPONENTS_PM_TEST_TOOLS
int pm_test_tools_init(void);
#endif /* CONFIG_COMPONENTS_PM_TEST_TOOLS */

#endif


