/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __PLAT_FC_SUN20IW2_H__
#define __PLAT_FC_SUN20IW2_H__

#define PLAT_FC_MAX_NUM 1

/*!< Peripheral memory map */
#define PLAT_FC_PERI_BASE_ADDR (0x40000000U)

#define PLAT_FC_REG_BASE_ADDR (PLAT_FC_PERI_BASE_ADDR + 0x0000B000)
#define PLAT_FC_ENC_BASE_ADDR (PLAT_FC_PERI_BASE_ADDR + 0x0003F800)

#define PLAT_FC_MEM_MAP_START_ADDR (0x10000000)
#define PLAT_FC_MEM_MAP_END_ADDR (0x1C000000 - 1)

#define PLAT_FC_INPUT_CLK_TYPE HAL_SUNXI_CCU
#define PLAT_FC_INPUT_CLK_ID CLK_FLASH_SPI

#define PLAT_FC_PARENT_CLK_TYPE HAL_SUNXI_AON_CCU
#define PLAT_FC_PARENT_CLK_ID CLK_DEVICE

#define PLAT_FC_RESET_TYPE HAL_SUNXI_RESET
#define PLAT_FC_RESET_ID RST_FLASH_CTRL

#define PLAT_FC_ENC_RESET_TYPE HAL_SUNXI_RESET
#define PLAT_FC_ENC_RESET_ID RST_FLASH_ENC

#define PLAT_FC_PIN_NUM 6

#endif /*__PLAT_FC_SUN20IW2_H__  */
