/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "plat_fc_sun20iw2.h"
#include "plat_fc_common.h"

__attribute__((unused)) fc_pinmux_info_t g_integrated_nor_pinmux[PLAT_FC_PIN_NUM] =
{
	{
		/* pin0: WP/IO2 */
		.pin = GPIOB(8),
		.func = GPIO_MUXSEL_FUNCTION2,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_UP,
	},
	{
		/* pin1: HOLD/IO3 */
		.pin = GPIOB(9),
		.func = GPIO_MUXSEL_FUNCTION2,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_UP,
	},
	{
		/* pin2: MOSI/IO0 */
		.pin = GPIOB(10),
		.func = GPIO_MUXSEL_FUNCTION2,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_DOWN_DISABLED,
	},
	{
		/* pin3: MISO/IO1 */
		.pin = GPIOB(11),
		.func = GPIO_MUXSEL_FUNCTION2,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_DOWN_DISABLED,
	},
	{
		/* pin4: CS */
		.pin = GPIOB(12),
		.func = GPIO_MUXSEL_FUNCTION2,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_UP,
	},
	{
		/* pin5: CLK */
		.pin = GPIOB(13),
		.func = GPIO_MUXSEL_FUNCTION2,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_DOWN_DISABLED,
	},
};

__attribute__((unused)) fc_pinmux_info_t g_external_nor_pinmux[PLAT_FC_PIN_NUM] =
{
	{
		/* pin0: CS */
		.pin = GPIOB(4),
		.func = GPIO_MUXSEL_FUNCTION5,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_UP,
	},
	{
		/* pin1: MOSI/IO0 */
		.pin = GPIOB(5),
		.func = GPIO_MUXSEL_FUNCTION5,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_DOWN_DISABLED,
	},
	{
		/* pin2: CLK */
		.pin = GPIOB(6),
		.func = GPIO_MUXSEL_FUNCTION5,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_DOWN_DISABLED,
	},
	{
		/* pin3: HOLD/IO3 */
		.pin = GPIOB(7),
		.func = GPIO_MUXSEL_FUNCTION5,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_UP,
	},
	{
		/* pin4: WP/IO2 */
		.pin = GPIOB(14),
		.func = GPIO_MUXSEL_FUNCTION5,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_UP,
	},
	{
		/* pin5: MISO/IO1 */
		.pin = GPIOB(15),
		.func = GPIO_MUXSEL_FUNCTION5,
		.drv_level = GPIO_DRIVING_LEVEL3,
		.pull_cfg = GPIO_PULL_DOWN_DISABLED,
	},
};

int plat_is_integrated_spi_nor(void)
{
	int HAL_PRCM_IsFlashSip(void);
	return HAL_PRCM_IsFlashSip();
}

