/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "type.h"

#define M33_SYST_CSR   0xe000e010
#define M33_SYST_RVR   0xe000e014
#define M33_SYST_CVR   0xe000e018
#define M33_SYST_CALIB 0xe000e01c

#define M33_SCB_CPUID  0xe000ed00
#define M33_SCB_ICSR   0xe000ed04
#define M33_SCB_VTOR   0xe000ed08
#define M33_SCB_AIRCR  0xe000ed0c
#define M33_SCB_SCR    0xe000ed10
#define M33_SCB_CCR    0xe000ed14

enum {
	CONTEXT_SYSTICK_CSR,
	CONTEXT_SYSTICK_RVR,

	CONTEXT_TOTAL_NUMBER,
};

u32 volatile cpu_systick_context[CONTEXT_TOTAL_NUMBER];

void cpu_disable_systick(void)
{
	volatile u32 value;

	/*save reload value*/
	cpu_systick_context[CONTEXT_SYSTICK_CSR] = readl(M33_SYST_CSR);
	cpu_systick_context[CONTEXT_SYSTICK_RVR] = readl(M33_SYST_RVR);

	/*close timer, intterupt*/
	value = readl(M33_SYST_CSR);
	value = value & ~0x3;
	writel(value, M33_SYST_CSR);

	/*clear pending*/
	value = readl(M33_SCB_ICSR);
	value = value & (0x1<<25);
	writel(value, M33_SCB_ICSR);
}

void cpu_enable_systick(void)
{
	volatile u32 value;

	/* restore reload value*/
	writel(cpu_systick_context[CONTEXT_SYSTICK_RVR], M33_SYST_RVR);

	/*clear counter*/
	writel(0x0, M33_SYST_CVR);

	/* restore control*/
	writel(cpu_systick_context[CONTEXT_SYSTICK_CSR], M33_SYST_CSR);
}

