# Allwinner Audio Driver device
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_DEVICE) += sunxi_sound_device.o

# Allwinner Audio Driver device core
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_DEVICE_CORE) += sunxi_sound_core.o sunxi_sound_io.o

# Allwinner Audio Driver Control
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_CONTROL) += sunxi_sound_control.o

# Allwinner Audio Driver pcm lib
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_PCM_LIB) += sunxi_sound_pcm_lib.o

# Allwinner Audio Driver pcm dma
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_PCM_DMA) += sunxi_sound_pcm_dma.o

# Allwinner Audio Driver pcm
obj-$(CONFIG_SUNXI_SOUND_AUDIO_DRIVER_PCM) += sunxi_sound_pcm.o sunxi_sound_pcm_misc.o

