obj-$(CONFIG_CUSTOMER_STREAM_TEST) += boot_mp3.o custom_stream_test.o customer_stream.o psram_stream.o

RTPLAYER_INCLUDE_DIR := components/aw/multimedia/include

CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/stream/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/base/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/include/cedarx/xplayer/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/playback/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/Cdx2.0Plugin/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/parser/include/
CFLAGS += -Werror