# Sunxi Common
obj-$(CONFIG_SUNXI_SOUND_COMMON_SUNXI_COMMON) += sunxi_sound_common.o

# Sunxi RX SYNC
obj-$(CONFIG_SUNXI_SOUND_RXSYNC) += sunxi_sound_rxsync.o

# Sunxi Alg Config
obj-$(CONFIG_SUNXI_SOUND_COMMON_ALG_CFG) += sunxi_sound_alg_cfg.o
