#ifndef __LANG_CONFIG_H__
#define __LANG_CONFIG_H__

typedef enum {
    ACCESS_VIA_BROWSER,
    ACTIVATION,
    BATTERY_CHARGING,
    BATTERY_FULL,
    BATTERY_LOW,
    BATTERY_NEED_CHARGE,
    CONNECTED_TO,
    CONNECTING,
    CONNECT_TO,
    CONNECT_TO_HOTSPOT,
    DETECTING_MODULE,
    ENTERING_WIFI_CONFIG_MODE,
    ERROR,
    INFO,
    INITIALIZING,
    LISTENING,
    LOADING_PROTOCOL,
    MAX_VOLUME,
    MUTED,
    NEW_VERSION,
    OTA_UPGRADE,
    PIN_ERROR,
    REGISTERING_NETWORK,
    REG_ERROR,
    SCANNING_WIFI,
    SERVER_ERROR,
    SERVER_NOT_CONNECTED,
    SERVER_NOT_FOUND,
    SERVER_TIMEOUT,
    SPEAKING,
    STANDBY,
    UPGRADE_FAILED,
    UPGRADING,
    VERSION,
    VOLUME,
    WARNING,
    WIFI_CONFIG_MODE,
    STRING_COUNT
} string_index;


const char* const lang_strings[] = {
    "浏览器访问",
    "激活设备",
    "正在充电",
    "电量已满",
    "电量不足",
    "电量低，请充电",
    "已连接 ",
    "连接中...",
    "连接 ",
    "手机连接热点 ",
    "检测模组...",
    "进入配网模式...",
    "错误",
    "信息",
    "正在初始化...",
    "聆听中...",
    "加载协议...",
    "最大音量",
    "已静音",
    "新版本 ",
    "OTA 升级",
    "请插入 SIM 卡",
    "等待网络...",
    "无法接入网络，请检查流量卡状态",
    "扫描 Wi-Fi...",
    "发送失败，请检查网络",
    "无法连接服务，请稍后再试",
    "正在寻找可用服务",
    "等待响应超时",
    "说话中...",
    "待命",
    "升级失败",
    "正在升级系统...",
    "版本 ",
    "音量 ",
    "警告",
    "配网模式"
};
#endif
