/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN300IW1_APP_CCU_H__
#define __SUN300IW1_APP_CCU_H__

#define APP_CCU_REG_BASE      0x42001000

enum sun300iw1_app_ccu_clk_id
{
	CLK_APP_DRAM,
	CLK_APP_E907_TS,
	CLK_APP_AL27_MT,
	CLK_APP_SMHC0,
	CLK_APP_SS,
	CLK_APP_SPI,
	CLK_APP_SPIF,
	CLK_APP_MCSI,
	CLK_APP_CSI_MASTER0,
	CLK_APP_CSI_MASTER1,
	CLK_APP_SPI2,
	CLK_APP_TCONLCD,
	CLK_APP_DE,
	CLK_APP_G2D,
	CLK_APP_GPADC0_24M,
	CLK_APP_VE,
	CLK_APP_AUDIO_DAC,
	CLK_APP_AUDIO_ADC,
	CLK_APP_I2S0,
	CLK_APP_SMHC1,
	CLK_APP_PLL_AUDIO_4X,
	CLK_APP_PLL_AUDIO_1X,
	CLK_APP_SPI1,
	CLK_APP_GMAC_FANOUT,
	CLK_APP_A27_MSGBOX,
	CLK_APP_USB_24M,
	CLK_APP_USB_12M,
	CLK_APP_USB_48M,
	CLK_APP_AVS,
	CLK_APP_GMAC_25M,
	CLK_APP_BUS_DPSS_TOP,
	CLK_APP_BUS_GPIO,
	CLK_APP_MCSI_AHB,
	CLK_APP_MBUS_MCSI,
	CLK_APP_VID_OUT,
	CLK_APP_MBUS_VID_OUT,
	CLK_APP_HBUS_GMAC,
	CLK_APP_USBOHCI,
	CLK_APP_USBEHCI,
	CLK_APP_USBOTG,
	CLK_APP_USB,
	CLK_APP_UART3,
	CLK_APP_UART2,
	CLK_APP_UART1,
	CLK_APP_UART0,
	CLK_APP_TWI0,
	CLK_APP_PWM,
	CLK_APP_TRNG,
	CLK_APP_TIMER,
	CLK_APP_SG_DMA,
	CLK_APP_DMA,
	CLK_APP_SYSCRTL,
	CLK_APP_CE,
	CLK_APP_HSTIMER,
	CLK_APP_SPLOCK,
	CLK_APP_BUS_DRAM,
	CLK_APP_RV_MSGBOX,
	CLK_APP_RISCV,
	CLK_APP_MBUS_G2D,
	CLK_APP_BUS_G2D,
	CLK_APP_G2D_HB,
	CLK_APP_TWI2,
	CLK_APP_TWI1,
	CLK_APP_BUS_SPI2,
	CLK_APP_BUS_GMAC,
	CLK_APP_BUS_SMHC1,
	CLK_APP_BUS_SMHC0,
	CLK_APP_BUS_SPI1,
	CLK_APP_GBGSYS,
	CLK_APP_MBUS_GMAC,
	CLK_APP_MBUS_SMHC1,
	CLK_APP_MBUS_SMHC0,
	CLK_APP_MBUS_USB,
	CLK_APP_MBUS_DMA,
	CLK_APP_BUS_I2S0,
	CLK_APP_BUS_ADDA,
	CLK_APP_BUS_SPIF,
	CLK_APP_BUS_SPI,
	CLK_APP_BUS_VE_AHB,
	CLK_APP_MBUS_VE,
	CLK_APP_BUS_THS,
	CLK_APP_GPA,
	CLK_APP_HBUS_MCSI,
	CLK_APP_SBUS_MCSI,
	CLK_APP_BUS_MISP,
	CLK_APP_24M_DCAP_RES,
	CLK_APP_SD_MONITOR,
	CLK_APP_AHB_MONITOR,
	CLK_APP_SBUS_VE,
	CLK_APP_HBUS_VE,
	CLK_APP_BUS_TCON,
	CLK_APP_SGDMA,
	CLK_APP_BUS_DE,
	CLK_APP_DE_HB,

	APP_CCU_CLK_NUMBER,
};

/* for the id name of legacy clocks */
#define CLK_RV_MSGBOX CLK_APP_RV_MSGBOX
#define CLK_UART0 CLK_APP_UART0
#define CLK_UART1 CLK_APP_UART1
#define CLK_UART2 CLK_APP_UART2
#define CLK_UART3 CLK_APP_UART3
#define CLK_GPADC0_24M CLK_APP_GPADC0_24M

enum sun300iw1_app_ccu_rst_id
{
	RST_APP_BUS_DPSSTOP,
	RST_APP_BUS_MCSI,
	RST_APP_BUS_HRESETN_MCSI,
	RST_APP_BUS_G2D,
	RST_APP_BUS_DE,
	RST_APP_BUS_GMAC,
	RST_APP_BUS_USBPHY,
	RST_APP_BUS_USBOHCI,
	RST_APP_BUS_USBEHCI,
	RST_APP_BUS_USBOTG,
	RST_APP_BUS_USB,
	RST_APP_BUS_UART3,
	RST_APP_BUS_UART2,
	RST_APP_BUS_UART1,
	RST_APP_BUS_UART0,
	RST_APP_BUS_TWI0,
	RST_APP_BUS_PWM,
	RST_APP_BUS_TRNG,
	RST_APP_BUS_TIMER,
	RST_APP_BUS_SGDMA,
	RST_APP_BUS_DMA,
	RST_APP_BUS_SYSCTRL,
	RST_APP_BUS_CE,
	RST_APP_BUS_HSTIMER,
	RST_APP_BUS_SPLOCK,
	RST_APP_BUS_DRAM,
	RST_APP_BUS_RV_MSGBOX,
	RST_APP_BUS_RV_SYS_APB,
	RST_APP_BUS_RV,
	RST_APP_BUS_A27_CFG,
	RST_APP_BUS_A27_MSGBOX,
	RST_APP_BUS_A27,
	RST_APP_BUS_TWI2,
	RST_APP_BUS_TWI1,
	RST_APP_BUS_SPI2,
	RST_APP_BUS_SMHC1,
	RST_APP_BUS_SMHC0,
	RST_APP_BUS_SPI1,
	RST_APP_BUS_DGBSYS,
	RST_APP_BUS_MBUS,
	RST_APP_BUS_TCONLCD,
	RST_APP_BUS_TCON,
	RST_APP_BUS_I2S0,
	RST_APP_BUS_AUDIO,
	RST_APP_BUS_SPIF,
	RST_APP_BUS_SPI,
	RST_APP_BUS_VE,
	RST_APP_BUS_THS,
	RST_APP_BUS_GPADC,
	RST_APP_BUS_A27WFG,
	RST_APP_BUS_GPIOWDG,
	RST_APP_BUS_RV_WDG,
	RST_APP_BUS_E907,

	APP_CCU_RST_NUMBER,
};

/* for the id name of legacy resets */
#define RST_BUS_RV_MSGBOX RST_APP_BUS_RV_MSGBOX
#define RST_BUS_UART0 RST_APP_BUS_UART0
#define RST_BUS_UART1 RST_APP_BUS_UART1
#define RST_BUS_UART2 RST_APP_BUS_UART2
#define RST_BUS_UART3 RST_APP_BUS_UART3
#define RST_BUS_GPADC RST_APP_BUS_GPADC

#endif  /* __SUN300IW1_APP_CCU_H__ */
