obj-$(CONFIG_RTPLAYER_TEST) += demo/rtplayer_test/
obj-$(CONFIG_RTRECORDER_TEST) += demo/recorder_test/
obj-$(CONFIG_RTOPUS_TEST) += demo/opus_test/
obj-$(CONFIG_PLAY_FIFO) += demo/play_fifo/
obj-$(CONFIG_AVI_TEST) += demo/avi_test/
obj-$(CONFIG_MP4_TEST) += demo/mp4_test/
obj-$(CONFIG_CUSTOMER_STREAM_TEST) += demo/custom_stream_test/
obj-$(CONFIG_LIB_MULTIMEDIA_CROP) += cedarx/