/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN20IW2_GPRCM_CCU_H__
#define __SUN20IW2_GPRCM_CCU_H__

#define GPRCM_CCU_REG_BASE 0x40050000

enum sun20iw2_gprcm_ccu_clk_id
{
	CLK_GPRCM_SYSRTC_32K_MUX,
	CLK_GPRCM_SYS_32K_MUX,
	CLK_GPRCM_BLE_32K_MUX,
	CLK_GPRCM_LFCLK_MUX,
	CLK_GPRCM_LOSC_GATE,
	CLK_GPRCM_RC_LF_GATE,
	CLK_GPRCM_RC_HF_GATE,
	CLK_GPRCM_RC_LF_FIXED_DIV,
	CLK_GPRCM_RCCAL_OUT,
	CLK_GPRCM_RCCAL_WUP_EN,
	CLK_GPRCM_HOSC_DIV,
	CLK_GPRCM_BLE_32M_DIV,
	CLK_GPRCM_BLE_32K_2,
	//CLK_GPRCM_INTERNAL_BLE_32K,
	CLK_GPRCM_BLE_32K_AUTO_SWITCH_EN,

	GPRCM_CCU_CLK_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define CLK_HOSC_DIV_32K CLK_GPRCM_HOSC_DIV
#define CLK_RCOSC_DIV_32K CLK_GPRCM_RC_LF_FIXED_DIV
#define CLK_OSC32K_EN CLK_GPRCM_LOSC_GATE
#define CLK_RC32K_EN CLK_GPRCM_RC_LF_GATE
#define RC_HF_EN CLK_GPRCM_HOSC_DIV
//#define CLK_RC_HF_GATE CLK_GPRCM_RC_HF_GATE
#define CLK_SYS_32K_SEL CLK_GPRCM_SYS_32K_MUX
#define CLK_BLE_SEL CLK_GPRCM_BLE_32K_MUX
#define CLK_SYSRTC32K CLK_GPRCM_SYSRTC_32K_MUX
#define CLK_LF_SEL CLK_GPRCM_LFCLK_MUX
//#define CLK_PAD CLK_GPRCM_PAD
//#define CLK_PAD_OUT CLK_GPRCM_PAD_OUT
#define CLK_RCCAL32K CLK_GPRCM_RCCAL_OUT
#define CLK_DIV CLK_GPRCM_BLE_32K_2
#define CLK_32K_AUTO_SWITCH CLK_GPRCM_BLE_32K_AUTO_SWITCH_EN
#define CLK_RCO_WUP_EN CLK_GPRCM_RCCAL_WUP_EN

enum sun20iw2_gprcm_ccu_rst_id
{
	GPRCM_CCU_RST_NUMBER,
};

#endif
