/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN20IW2_APP_CCU_H__
#define __SUN20IW2_APP_CCU_H__

#define APP_CCU_REG_BASE      0x4003C000

enum sun20iw2_app_ccu_clk_id
{
	CLK_APP_BUS_USB_EHCI_GATE,
	CLK_APP_BUS_USB_OHCI_GATE,
	CLK_APP_BUS_CSI_JPE_GATE,
	CLK_APP_BUS_LEDC_GATE,
	CLK_APP_BUS_USB_OTG_GATE,
	CLK_APP_BUS_SMCARD_GATE,
	CLK_APP_BUS_HSPSRAM_CTRL_GATE,
	CLK_APP_BUS_IR_RX_GATE,
	CLK_APP_BUS_IR_TX_GATE,
	CLK_APP_BUS_PWM_GATE,
	CLK_APP_BUS_TWI0_GATE,
	CLK_APP_BUS_TWI1_GATE,
	CLK_APP_BUS_UART0_GATE,
	CLK_APP_BUS_UART1_GATE,
	CLK_APP_BUS_UART2_GATE,
	CLK_APP_BUS_SDC0_GATE,
	CLK_APP_BUS_SPI0_GATE,
	CLK_APP_BUS_SPI1_GATE,

	CLK_APP_BUS_AHB_MONITOR_GATE,
	CLK_APP_BUS_G2D_GATE,
	CLK_APP_BUS_DE_GATE,
	CLK_APP_BUS_DISPLAY_GATE,
	CLK_APP_BUS_LCD_GATE,
	CLK_APP_BUS_BT_CORE_GATE,
	CLK_APP_BUS_WLAN_CTRL_GATE,
	CLK_APP_BUS_TRNG_GATE,
	CLK_APP_BUS_SPC_GATE,
	CLK_APP_BUS_SS_GATE,
	CLK_APP_BUS_TIMER_GATE,
	CLK_APP_BUS_SPINLOCK_GATE,
	CLK_APP_BUS_DMA0_GATE,
	CLK_APP_BUS_DMA1_GATE,
	CLK_APP_BUS_SPDIF_GATE,
	CLK_APP_BUS_I2S_GATE,

	CLK_APP_C906_CFG_GATE,
	CLK_APP_C906_MSGBOX_GATE,
	CLK_APP_HIFI5_CFG_GATE,
	CLK_APP_HIFI5_MSGBOX_GATE,
	CLK_APP_M33_MSGBOX_GATE,
	CLK_APP_MBUS_DE_GATE,
	CLK_APP_MBUS_G2D_GATE,
	CLK_APP_MBUS_CSI_GATE,
	CLK_APP_MBUS_DMA0_GATE,
	CLK_APP_MBUS_DMA1_GATE,
	CLK_APP_MBUS_USB_GATE,
	CLK_APP_MBUS_CE_GATE,
	CLK_APP_MBUS_HIFI5_GATE,
	CLK_APP_MBUS_C906_GATE,
	CLK_APP_MBUS_M33_GATE,

	CLK_APP_SPI0,
	CLK_APP_SPI1,
	CLK_APP_SDC0,
	CLK_APP_SS,
	CLK_APP_CSI_JPE,
	CLK_APP_LEDC,
	CLK_APP_IR_RX,
	CLK_APP_IR_TX,
	CLK_APP_SYSTICK_REF,
	CLK_APP_SYSTICK_NOREF_GATE,
	CLK_APP_SYSTICK_SKEW_GATE,
	CLK_APP_CSI,
	CLK_APP_FLASH_CONTROLLER,
	CLK_APP_APB_SPC,
	CLK_APP_USB_MUX,
	//CLK_APP_C906,
	CLK_APP_C906_MUX,
	CLK_APP_C906_GATE,
	CLK_APP_C906_DIV,
	CLK_APP_C906_AXI_DIV,
	CLK_APP_HIFI5_MUX,
	CLK_APP_HIFI5_GATE,
	CLK_APP_HIFI5_DIV,

	CLK_APP_HSPSRAM_FIXED_DIV,
	CLK_APP_HSPSRAM_GATE,
	CLK_APP_LSPSRAM,
	CLK_APP_LSPSRAM_FIXED_DIV,

	CLK_APP_G2D,
	CLK_APP_DE,
	CLK_APP_LCD,

	APP_CCU_CLK_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
//#define CLK_OSC12M CLK_APP_OSC12M
#define CLK_BUS_PWM CLK_APP_BUS_PWM_GATE
#define CLK_BUS_TWI1 CLK_APP_BUS_TWI1_GATE
#define CLK_BUS_TWI0 CLK_APP_BUS_TWI0_GATE
#define CLK_BUS_UART0 CLK_APP_BUS_UART0_GATE
#define CLK_BUS_UART1 CLK_APP_BUS_UART1_GATE
#define CLK_BUS_UART2 CLK_APP_BUS_UART2_GATE
#define CLK_BUS_SDC0 CLK_APP_BUS_SDC0_GATE
#define CLK_BUS_SPI0 CLK_APP_BUS_SPI0_GATE
#define CLK_BUS_SPI1 CLK_APP_BUS_SPI1_GATE
#define CLK_BUS_MONITOR CLK_APP_BUS_AHB_MONITOR_GATE
#define CLK_BUS_G2D CLK_APP_BUS_G2D_GATE
#define CLK_BUS_DE CLK_APP_BUS_DE_GATE
#define CLK_BUS_DISPLAY CLK_APP_BUS_DISPLAY_GATE
#define CLK_BUS_LCD CLK_APP_BUS_LCD_GATE
#define CLK_BUS_BT_CORE CLK_APP_BUS_BT_CORE_GATE
#define CLK_BUS_WLAN_CTRL CLK_APP_BUS_WLAN_CTRL_GATE
#define CLK_BUS_TRNG CLK_APP_BUS_TRNG_GATE
#define CLK_BUS_SPC CLK_APP_BUS_SPC_GATE
#define CLK_BUS_SS CLK_APP_BUS_SS_GATE
#define CLK_BUS_TIMER CLK_APP_BUS_TIMER_GATE
#define CLK_BUS_SPINLOCK CLK_APP_BUS_SPINLOCK_GATE
#define CLK_BUS_DMA1 CLK_APP_BUS_DMA1_GATE
#define CLK_BUS_DMA0 CLK_APP_BUS_DMA0_GATE
#define CLK_BUS_SPDIF CLK_APP_BUS_SPDIF_GATE
#define CLK_BUS_I2S CLK_APP_BUS_I2S_GATE
#define CLK_RISCV_CFG CLK_APP_C906_CFG_GATE
#define CLK_RISCV_MSGBOX CLK_APP_C906_MSGBOX_GATE
#define CLK_DSP_CFG CLK_APP_HIFI5_CFG_GATE
#define CLK_DSP_MSGBOX CLK_APP_HIFI5_MSGBOX_GATE
#define CLK_CPU_MSGBOX CLK_APP_M33_MSGBOX_GATE
#define CLK_MBUS_DE CLK_APP_MBUS_DE_GATE
#define CLK_MBUS_G2D CLK_APP_MBUS_G2D_GATE
#define CLK_MBUS_CSI CLK_APP_MBUS_CSI_GATE
#define CLK_MBUS_DMA1 CLK_APP_MBUS_DMA1_GATE
#define CLK_MBUS_DMA0 CLK_APP_MBUS_DMA0_GATE
#define CLK_MBUS_USB CLK_APP_MBUS_USB_GATE
#define CLK_MBUS_CE CLK_APP_MBUS_CE_GATE
#define CLK_MBUS_DSP CLK_APP_MBUS_HIFI5_GATE
#define CLK_MBUS_RISCV CLK_APP_MBUS_C906_GATE
#define CLK_MBUS_CPU CLK_APP_MBUS_M33_GATE
#define CLK_SPI0 CLK_APP_SPI0
#define CLK_SPI1 CLK_APP_SPI1
#define CLK_SDC0 CLK_APP_SDC0
#define CLK_SS CLK_APP_SS
#define CLK_CSI_JPE CLK_APP_CSI_JPE
#define CLK_LEDC CLK_APP_LEDC
#define CLK_IRRX CLK_APP_IR_RX
#define CLK_IRTX CLK_APP_IR_TX
#define CLK_SYSTICK_REF CLK_APP_SYSTICK_REF
#define CLK_SYSTICK_NOREF CLK_APP_SYSTICK_NOREF_GATE
#define CLK_SYSTICK_SKEW CLK_APP_SYSTICK_SKEW_GATE
#define CLK_CSI_MCLK CLK_APP_CSI
#define CLK_FLASH_SPI CLK_APP_FLASH_CONTROLLER
#define CLK_PCLK_SPC CLK_APP_APB_SPC
#define CLK_USB_PLL CLK_APP_USB_MUX
#define CLK_RISCV_GATE CLK_APP_C906_GATE
#define CLK_RISCV_AXI CLK_APP_C906_AXI_DIV
#define CLK_RISCV_SEL CLK_APP_C906_MUX
#define CLK_RISCV_DIV CLK_APP_C906_DIV
#define CLK_DSP_GATE CLK_APP_HIFI5_GATE
#define CLK_DSP_SEL CLK_APP_HIFI5_MUX
#define CLK_DSP_DIV CLK_APP_HIFI5_DIV
#define CLK_HSPSRAM_GATE CLK_APP_HSPSRAM_GATE
#define CLK_HSPSRAM_CTRL CLK_APP_HSPSRAM_FIXED_DIV
#define CLK_LSPSRAM_GATE CLK_APP_LSPSRAM_GATE
#define CLK_LSPSRAM_SEL CLK_APP_LSPSRAM_MUX
#define CLK_LSPSRAM_DIV CLK_APP_LSPSRAM_DIV
#define CLK_LSPSRAM_CTRL CLK_APP_LSPSRAM_FIXED_DIV
#define CLK_IR_RX CLK_APP_BUS_IR_RX_GATE
#define CLK_IR_TX CLK_APP_BUS_IR_TX_GATE
#define CLK_BUS_OHCI0 CLK_APP_BUS_USB_OHCI_GATE
#define CLK_BUS_CSI_JPE CLK_APP_BUS_CSI_JPE_GATE
#define CLK_BUS_EHCI0 CLK_APP_BUS_USB_EHCI_GATE
#define CLK_BUS_OTG CLK_APP_BUS_USB_OTG_GATE
#define CLK_BUS_SMCARD CLK_APP_BUS_SMCARD_GATE
#define CLK_BUS_HSPSRAM_CTRL CLK_APP_BUS_HSPSRAM_CTRL_GATE
#define CLK_BUS_LEDC CLK_APP_BUS_LEDC_GATE
#define CLK_G2D CLK_APP_G2D
#define CLK_DE CLK_APP_DE
#define CLK_LCD CLK_APP_LCD


enum sun20iw2_app_ccu_rst_id
{
	RST_APP_USB_EHCI,
	RST_APP_USB_OHCI,
	RST_APP_CSI_JPE,
	RST_APP_LEDC,
	RST_APP_USB_OTG,
	RST_APP_SMCARD,
	RST_APP_USB_PHY,
	RST_APP_FLASH_ENC,
	RST_APP_FLASH_CTRL,
	RST_APP_HSPSRAM_CTRL,
	RST_APP_LSPSRAM_CTRL,
	RST_APP_IRRX,
	RST_APP_IRTX,
	RST_APP_PWM,
	RST_APP_TWI1,
	RST_APP_TWI0,
	RST_APP_UART2,
	RST_APP_UART1,
	RST_APP_UART0,
	RST_APP_SDC0,
	RST_APP_SPI1,
	RST_APP_SPI0,
	RST_APP_G2D,
	RST_APP_DE,
	RST_APP_DISPLAY,
	RST_APP_LCD,
	RST_APP_BT_CORE,
	RST_APP_WLAN_CTRL,
	RST_APP_TRNG,
	RST_APP_SPC,
	RST_APP_SS,
	RST_APP_TIMER,
	RST_APP_SPINLOCK,
	RST_APP_DMA1,
	RST_APP_DMA0,
	RST_APP_SPDIF,
	RST_APP_I2S,
	RST_APP_C906_SYS_APB_SOFT,
	RST_APP_C906_TIMESTAMP,
	RST_APP_C906_CFG,
	RST_APP_C906_MSGBOX,
	RST_APP_C906_WDG,
	RST_APP_C906_CORE,
	RST_APP_HIFI5_DEBUG,
	RST_APP_HIFI5_INTC,
	RST_APP_HIFI5_TZMA,
	RST_APP_HIFI5_CFG,
	RST_APP_HIFI5_MSGBOX,
	RST_APP_HIFI5_WDG,
	RST_APP_HIFI5_CORE,
	RST_APP_M33_CFG,
	RST_APP_M33_MSGBOX,
	RST_APP_M33_WDG,

	APP_CCU_RST_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define RST_USB_EHCI RST_APP_USB_EHCI
#define RST_USB_OHCI RST_APP_USB_OHCI
#define RST_CSI_JPE RST_APP_CSI_JPE
#define RST_LEDC RST_APP_LEDC
#define RST_USB_OTG RST_APP_USB_OTG
#define RST_SMCARD RST_APP_SMCARD
#define RST_USB_PHY RST_APP_USB_PHY
#define RST_FLASH_ENC RST_APP_FLASH_ENC
#define RST_FLASH_CTRL RST_APP_FLASH_CTRL
#define RST_HSPSRAM_CTRL RST_APP_HSPSRAM_CTRL
#define RST_LSPSRAM_CTRL RST_APP_LSPSRAM_CTRL
#define RST_IRRX RST_APP_IRRX
#define RST_IRTX RST_APP_IRTX
#define RST_PWM RST_APP_PWM
#define RST_TWI1 RST_APP_TWI1
#define RST_TWI0 RST_APP_TWI0
#define RST_UART2 RST_APP_UART2
#define RST_UART1 RST_APP_UART1
#define RST_UART0 RST_APP_UART0
#define RST_SDC0 RST_APP_SDC0
#define RST_SPI1 RST_APP_SPI1
#define RST_SPI0 RST_APP_SPI0
#define RST_G2D RST_APP_G2D
#define RST_DE RST_APP_DE
#define RST_DISPLAY RST_APP_DISPLAY
#define RST_LCD RST_APP_LCD
#define RST_BT_CORE RST_APP_BT_CORE
#define RST_WLAN_CTRL RST_APP_WLAN_CTRL
#define RST_TRNG RST_APP_TRNG
#define RST_SPC RST_APP_SPC
#define RST_SS RST_APP_SS
#define RST_TIMER RST_APP_TIMER
#define RST_SPINLOCK RST_APP_SPINLOCK
#define RST_DMA1 RST_APP_DMA1
#define RST_DMA0 RST_APP_DMA0
#define RST_SPDIF RST_APP_SPDIF
#define RST_I2S RST_APP_I2S
#define RST_RISCV_TIMESTAMP RST_APP_C906_TIMESTAMP
#define RST_RISCV_SYS_APB_SOFT RST_APP_C906_SYS_APB_SOFT
#define RST_RISCV_CFG RST_APP_C906_CFG
#define RST_RISCV_MSGBOX RST_APP_C906_MSGBOX
#define RST_RISCV_WDG RST_APP_C906_WDG
#define RST_RISCV_CORE RST_APP_C906_CORE
#define RST_DSP_DEBUG RST_APP_HIFI5_DEBUG
#define RST_DSP_INTC RST_APP_HIFI5_INTC
#define RST_DSP_TZMA RST_APP_HIFI5_TZMA
#define RST_DSP_CFG RST_APP_HIFI5_CFG
#define RST_DSP_MSGBOX RST_APP_HIFI5_MSGBOX
#define RST_DSP_WDG RST_APP_HIFI5_WDG
#define RST_DSP_CORE RST_APP_HIFI5_CORE
#define RST_CPU_CFG RST_APP_M33_CFG
#define RST_CPU_MSGBOX RST_APP_M33_MSGBOX
#define RST_CPU_WDG RST_APP_M33_WDG

#endif  /* __SUN20IW2_APP_CCU_H__ */
