/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 *the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __SUN20IW2_AON_CCU_H__
#define __SUN20IW2_AON_CCU_H__

#define AON_CCU_REG_BASE      0x4004C400  /* CCU_AON */

enum sun20iw2_aon_ccu_clk_id
{
	CLK_AON_HOSC_FAKE_MUX,
	CLK_AON_DPLL1_PRE_DIV,
	CLK_AON_DPLL1,
	CLK_AON_DPLL2_PRE_DIV,
	CLK_AON_DPLL2,
	CLK_AON_DPLL3_PRE_DIV,
	CLK_AON_DPLL3,
	CLK_AON_RFIP0_DPLL,
	CLK_AON_RFIP1_DPLL,
	//CLK_AON_PLL_AUDIO_PRE_DIV,
	CLK_AON_PLL_AUDIO,
	CLK_AON_PLL_AUDIO_POST_DIV,
	//CLK_AON_PLL_AUDIO_POST_MULT,
	CLK_AON_PLL_AUDIO1X,
	CLK_AON_PLL_AUDIO2X,

	CLK_AON_CK1_USB,
	CLK_AON_CK1_AUDIO,
	CLK_AON_CK1_DEV,
	CLK_AON_CK1_LSPSRAM,
	CLK_AON_CK1_HSPSRAM_FAKE_PRE_MULT,
	CLK_AON_CK1_HSPSRAM,
	CLK_AON_CK1_HIFI5,
	CLK_AON_CK1_C906_FAKE_PRE_MULT,
	CLK_AON_CK1_C906,
	CLK_AON_CK1_M33,

	CLK_AON_CK3_DEV,
	CLK_AON_CK3_LSPSRAM,
	CLK_AON_CK3_HSPSRAM_FAKE_PRE_MULT,
	CLK_AON_CK3_HSPSRAM,
	CLK_AON_CK3_HIFI5,
	CLK_AON_CK3_C906_FAKE_PRE_MULT,
	CLK_AON_CK3_C906,
	CLK_AON_CK3_M33,

	CLK_AON_LDO_BYPASS,
	CLK_AON_LDO2_EN,
	CLK_AON_LDO1_EN,
#if 0
	CLK_AON_WLAN_BT_DEBUG_SEL0,
	CLK_AON_WLAN_BT_DEBUG_SEL1,
	CLK_AON_WLAN_BT_DEBUG_SEL2,
	CLK_AON_WLAN_BT_DEBUG_SEL3,
	CLK_AON_WLAN_BT_DEBUG_SEL4,
	CLK_AON_WLAN_BT_DEBUG_SEL5,
	CLK_AON_WLAN_BT_DEBUG_SEL6,
	CLK_AON_WLAN_BT_DEBUG_SEL7,
#endif
	CLK_AON_WLAN_MUX,
	CLK_AON_BT_MUX,
	CLK_AON_RFIP2_EN,
	CLK_AON_BLE_32M_GATE,
	CLK_AON_BLE_48M_GATE,
	CLK_AON_BUS_MAD_AHB_GATE,
	CLK_AON_BUS_GPIO_GATE,
	CLK_AON_BUS_CODEC_DAC_GATE,
	CLK_AON_BUS_RCCAL_GATE,
	CLK_AON_BUS_CODEC_ADC_GATE,
	CLK_AON_BUS_MAD_APB_GATE,
	CLK_AON_BUS_DMIC_GATE,
	CLK_AON_BUS_GPADC_GATE,
	CLK_AON_BUS_LPUART1_WKUP_GATE,
	CLK_AON_BUS_LPUART0_WKUP_GATE,
	CLK_AON_LPUART0,
	CLK_AON_LPUART1,
	CLK_AON_GPADC,
	CLK_AON_DMIC_GATE,
	CLK_AON_SPDIF_TX,
	CLK_AON_I2S,
	CLK_AON_CODEC_DAC,
	CLK_AON_CODEC_ADC_MUX,
	CLK_AON_CODEC_ADC_GATE,
	CLK_AON_AUDPLL_HOSC_MUX,
	CLK_AON_CODEC_ADC_PRE,
	CLK_AON_CK1_AUDIO_DIV,
	CLK_AON_RC_HF_DIV,

	CLK_AON_CK_HSPSRAM_MUX,
	CLK_AON_CK_LSPSRAM_MUX,
	CLK_AON_CK_M33_MUX,
	CLK_AON_CK_HIFI5_MUX,
	CLK_AON_CK_C906_MUX,
	CLK_AON_CK_DEV_MUX,
	CLK_AON_CK_M33_DIV,
	CLK_AON_AHB_MUX,

	CLK_AON_HOSC_TO_APB_DIV,
	CLK_AON_SYS_32K_TO_APB_DIV,
	CLK_AON_AHB_TO_APB_DIV,
	CLK_AON_APB_MUX,

	CLK_AON_DEVICE_DIV,

	CLK_AON_MAD_LPSD_PRE_DIV,
	CLK_AON_MAD_LPSD,
	CLK_AON_SPDIF_RX,
	CLK_AON_I2S_ASRC,

	AON_CCU_CLK_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define CLK_HOSC CLK_AON_HOSC_FAKE_MUX
#define CLK_DPLL1_PRE_DIV CLK_AON_DPLL1_PRE_DIV
#define CLK_DPLL1 CLK_AON_DPLL1
#define CLK_DPLL2_PRE_DIV CLK_AON_DPLL2_PRE_DIV
#define CLK_DPLL2 CLK_AON_DPLL2
#define CLK_DPLL3_PRE_DIV CLK_AON_DPLL3_PRE_DIV
#define CLK_DPLL3 CLK_AON_DPLL3
#define CLK_RFIP0_DPLL CLK_AON_RFIP0_DPLL
#define CLK_RFIP1_DPLL CLK_AON_RFIP1_DPLL
//#define CLK_PLL_AUDIO_PRE_DIV CLK_AON_PLL_AUDIO_PRE_DIV
#define CLK_PLL_AUDIO CLK_AON_PLL_AUDIO
#define CLK_PLL_AUDIO1X CLK_AON_PLL_AUDIO1X
#define CLK_PLL_AUDIO2X CLK_AON_PLL_AUDIO2X
#define CLK_CK1_USB CLK_AON_CK1_USB
#define CLK_CK1_AUD CLK_AON_CK1_AUDIO
#define CLK_CK1_DEV CLK_AON_CK1_DEV
#define CLK_CK1_LSPSRAM CLK_AON_CK1_LSPSRAM
#define CLK_CK1_HSPSRAM_PRE CLK_AON_CK1_HSPSRAM_FAKE_PRE_MULT
#define CLK_CK1_HSPSRAM CLK_AON_CK1_HSPSRAM
#define CLK_CK1_HIFI5 CLK_AON_CK1_HIFI5
#define CLK_CK1_C906_PRE CLK_AON_CK1_C906_FAKE_PRE_MULT
#define CLK_CK1_C906 CLK_AON_CK1_C906
#define CLK_CK1_M33 CLK_AON_CK1_M33
#define CLK_CK3_DEV CLK_AON_CK3_DEV
#define CLK_CK3_LSPSRAM CLK_AON_CK3_LSPSRAM
#define CLK_CK3_HSPSRAM_PRE CLK_AON_CK3_HSPSRAM_FAKE_PRE_MULT
#define CLK_CK3_HSPSRAM CLK_AON_CK3_HSPSRAM
#define CLK_CK3_HIFI5 CLK_AON_CK3_HIFI5
#define CLK_CK3_C906_PRE CLK_AON_CK3_C906_FAKE_PRE_MULT
#define CLK_CK3_C906 CLK_AON_CK3_C906
#define CLK_CK3_M33 CLK_AON_CK3_M33
#define CLK_LDO_BYPASS CLK_AON_LDO_BYPASS
#define CLK_LDO2_EN CLK_AON_LDO2_EN
#define CLK_LDO1_EN CLK_AON_LDO1_EN
#if 0
#define CLK_WLAN_BT_DEBUG_SEL0 CLK_AON_WLAN_BT_DEBUG_SEL0
#define CLK_WLAN_BT_DEBUG_SEL1 CLK_AON_WLAN_BT_DEBUG_SEL1
#define CLK_WLAN_BT_DEBUG_SEL2 CLK_AON_WLAN_BT_DEBUG_SEL2
#define CLK_WLAN_BT_DEBUG_SEL3 CLK_AON_WLAN_BT_DEBUG_SEL3
#define CLK_WLAN_BT_DEBUG_SEL4 CLK_AON_WLAN_BT_DEBUG_SEL4
#define CLK_WLAN_BT_DEBUG_SEL5 CLK_AON_WLAN_BT_DEBUG_SEL5
#define CLK_WLAN_BT_DEBUG_SEL6 CLK_AON_WLAN_BT_DEBUG_SEL6
#define CLK_WLAN_BT_DEBUG_SEL7 CLK_AON_WLAN_BT_DEBUG_SEL7
#endif
#define CLK_WLAN_SEL CLK_AON_WLAN_MUX
#define CLK_BT_SEL CLK_AON_BT_MUX
#define CLK_PFIP2_GATE CLK_AON_RFIP2_EN
#define CLK_BLE_32M CLK_AON_BLE_32M_GATE
#define CLK_BLE_48M CLK_AON_BLE_48M_GATE
#define CLK_MAD_AHB_GATE CLK_AON_BUS_MAD_AHB_GATE
#define CLK_GPIO_GATE CLK_AON_BUS_GPIO_GATE
#define CLK_BUS_CODEC_DAC CLK_AON_BUS_CODEC_DAC_GATE
#define CLK_RCCAL CLK_AON_BUS_RCCAL_GATE
#define CLK_BUS_CODEC_ADC CLK_AON_BUS_CODEC_ADC_GATE
#define CLK_MAD_APB_GATE CLK_AON_BUS_MAD_APB_GATE
#define CLK_BUS_DMIC CLK_AON_BUS_DMIC_GATE
#define CLK_GPADC CLK_AON_BUS_GPADC_GATE
#define CLK_LPUART1_WKUP CLK_AON_BUS_LPUART1_WKUP_GATE
#define CLK_LPUART0_WKUP CLK_AON_BUS_LPUART0_WKUP_GATE
#define CLK_LPUART0 CLK_AON_LPUART0
#define CLK_LPUART1 CLK_AON_LPUART1
#define CLK_GPADC_CTRL CLK_AON_GPADC
#define CLK_DMIC_GATE CLK_AON_DMIC_GATE
#define CLK_SPDIF_TX CLK_AON_SPDIF_TX
#define CLK_I2S CLK_AON_I2S
#define CLK_CODEC_DAC CLK_AON_CODEC_DAC
#define CLK_CODEC_ADC_SEL1 CLK_AON_CODEC_ADC_MUX
#define CLK_CODEC_ADC_GATE CLK_AON_CODEC_ADC_GATE
#define CLK_AUDPLL_HOSC_SEL CLK_AON_AUDPLL_HOSC_MUX
#define CLK_CODEC_ADC_DIV CLK_AON_CODEC_ADC_PRE
#define CLK_CK1_AUD_DIV CLK_AON_CK1_AUDIO_DIV
#define CLK_AUD_RCO_DIV CLK_AON_RC_HF_DIV
#define CLK_CKPLL_HSPSRAM_SEL CLK_AON_CK_HSPSRAM_MUX
#define CLK_CKPLL_LSPSRAM_SEL CLK_AON_CK_LSPSRAM_MUX
#define CLK_CK_M33 CLK_AON_CK_M33_MUX
#define CLK_CKPLL_HIFI5_SEL CLK_AON_CK_HIFI5_MUX
#define CLK_CKPLL_C906_SEL CLK_AON_CK_C906_MUX
#define CLK_CK_DEV CLK_AON_CK_DEV_MUX
#define CLK_SYS CLK_AON_CK_M33_DIV
#define CLK_AR200A_F CLK_AON_AHB_MUX
#define CLK_HFAON_DIV CLK_AON_HOSC_TO_APB_DIV
#define CLK_LFAON_DIV CLK_AON_SYS_32K_TO_APB_DIV
#define CLK_AHB_DIV CLK_AON_AHB_TO_APB_DIV
#define CLK_APB CLK_AON_APB_MUX
#define CLK_DEVICE CLK_AON_DEVICE_DIV
#define CLK_MAD_LPSD CLK_AON_MAD_LPSD
#define CLK_SPDIF_RX CLK_AON_SPDIF_RX
#define CLK_I2S_ASRC CLK_AON_I2S_ASRC


enum sun20iw2_aon_ccu_rst_id
{
	RST_AON_BLE_RTC,
	RST_AON_MADCFG,
	RST_AON_WLAN_CONN,
	RST_AON_WLAN,
	RST_AON_CODEC_DAC,
	RST_AON_RFAS,
	RST_AON_RCCAL,
	RST_AON_LPSD,
	RST_AON_AON_TIMER,
	RST_AON_CODEC_ADC,
	RST_AON_MAD,
	RST_AON_DMIC,
	RST_AON_GPADC,
	RST_AON_LPUART1,
	RST_AON_LPUART0,
	//RST_AON_BLE_32M,
	//RST_AON_BLE_48M,

	AON_CCU_RST_NUMBER,
};

/* provide some legacy macro to be compatible with legacy code  */
#define RST_BLE_RTC RST_AON_BLE_RTC
#define RST_MADCFG RST_AON_MADCFG
#define RST_WLAN_CONN RST_AON_WLAN_CONN
#define RST_WLAN RST_AON_WLAN
#define RST_CODEC_DAC RST_AON_CODEC_DAC
#define RST_RFAS RST_AON_RFAS
#define RST_RCCAL RST_AON_RCCAL
#define RST_LPSD RST_AON_LPSD
#define RST_AON_TIMER RST_AON_AON_TIMER
#define RST_CODEC_ADC RST_AON_CODEC_ADC
#define RST_MAD RST_AON_MAD
#define RST_DMIC RST_AON_DMIC
#define RST_GPADC RST_AON_GPADC
#define RST_LPUART1 RST_AON_LPUART1
#define RST_LPUART0 RST_AON_LPUART0

/* provide legacy API, not recommend to be used in new code*/
unsigned int HAL_GetHFClock(void);

#endif
